---
apiVersion: data.nais.io/v1
kind: Postgres
metadata:
  name: foobar
  namespace: someteamname
spec:
  cluster:
    majorVersion: "17"
    resources:
      cpu: 100m
      diskSize: 2Gi
      memory: 2G
  database:
    collation: nb_NO
