// Code generated by sqlc. DO NOT EDIT.
// source: checker.sql

package checkersql

import (
	"context"
)

const deleteIssues = `-- name: DeleteIssues :exec
DELETE FROM issues
`

func (q *Queries) DeleteIssues(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteIssues)
	return err
}
