apiVersion: v1
kind: Secret
metadata:
  name: unmanaged-secret-in-staging
type: Opaque
data:
  username: dXNlcm5hbWU= # username
  password: cGFzc3dvcmQ= # password
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    console.nais.io/last-modified-at: "2024-10-18T12:44:57Z"
    console.nais.io/last-modified-by: autheticated@example.com
    reloader.stakater.com/match: "true"
  labels:
    nais.io/managed-by: console
  name: managed-secret-in-staging
type: Opaque
data:
  username: dXNlcm5hbWU= # username
  password: cGFzc3dvcmQ= # password
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    console.nais.io/last-modified-at: "2024-10-18T12:44:57Z"
    console.nais.io/last-modified-by: autheticated@example.com
    reloader.stakater.com/match: "true"
  labels:
    nais.io/managed-by: console
  name: managed-secret-in-staging-used-with-filesfrom
type: Opaque
data:
  username: dXNlcm5hbWU= # username
  password: cGFzc3dvcmQ= # password
