// Code generated by sqlc. DO NOT EDIT.
// source: team_members.sql

package teamsapisql

import (
	"context"

	"github.com/nais/api/internal/slug"
)

const listMembers = `-- name: ListMembers :many
SELECT
	users.email
FROM
	users,
	user_roles
WHERE
	users.id = user_roles.user_id
	AND user_roles.target_team_slug = $1::slug
ORDER BY
	users.email ASC
`

func (q *Queries) ListMembers(ctx context.Context, teamSlug slug.Slug) ([]string, error) {
	rows, err := q.db.Query(ctx, listMembers, teamSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var email string
		if err := rows.Scan(&email); err != nil {
			return nil, err
		}
		items = append(items, email)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const teamExists = `-- name: TeamExists :one
SELECT
	EXISTS (
		SELECT
			slug
		FROM
			teams
		WHERE
			slug = $1
	)
`

func (q *Queries) TeamExists(ctx context.Context, argSlug slug.Slug) (bool, error) {
	row := q.db.QueryRow(ctx, teamExists, argSlug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
