version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    command:
      ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    ports:
      - "3002:5432"
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: api
      POSTGRES_DB: api
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    depends_on:
      - postgres
    image: adminer:latest
    ports:
      - "3003:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres

volumes:
  pgdata:
