services:
  postgres:
    image: postgres:15-alpine
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    ports:
      - "3002:5432"
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: api
      POSTGRES_DB: api
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    depends_on:
      - postgres
    image: adminer:latest
    ports:
      - "3003:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres

  pubsub:
    image: google/cloud-sdk
    platform: linux/x86_64 # this is required for running on M1 Mac
    command:
      - gcloud
      - beta
      - emulators
      - pubsub
      - start
      - --host-port=0.0.0.0:8085
    ports:
      - "3004:8085"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./hack/otel-collector-config.yaml:/etc/otel-collector-config.yml:ro
    ports:
      - "4317:4317" # OTLP gRPC receiver
    depends_on:
      - jaeger
    mem_limit: 100m

  bigquery:
    platform: linux/x86_64 # this is required for running on M1 Mac
    image: ghcr.io/goccy/bigquery-emulator:latest
    command:
      - "bigquery-emulator"
      - "--project=project"
      - "--dataset=dataset"
      - "--data-from-yaml=/data.yaml"
    ports:
      - "9050:9050"
    volumes:
      - ./hack/bigquery-emulator-data.yaml:/data.yaml

volumes:
  pgdata:
  dependency-track:
