services:
  postgres:
    image: postgres:15-alpine
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    ports:
      - "3002:5432"
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: api
      POSTGRES_DB: api
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    depends_on:
      - postgres
    image: adminer:latest
    ports:
      - "3003:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres

  pubsub:
    image: google/cloud-sdk
    platform: linux/x86_64 # this is required for running on M1 Mac
    command:
      - gcloud
      - beta
      - emulators
      - pubsub
      - start
      - --host-port=0.0.0.0:8085
    ports:
      - "3004:8085"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./hack/otel-collector-config.yaml:/etc/otel-collector-config.yml:ro
    ports:
      - "4317:4317" # OTLP gRPC receiver
    depends_on:
      - jaeger
    mem_limit: 100m

  bigquery:
    platform: linux/x86_64 # this is required for running on M1 Mac
    image: ghcr.io/goccy/bigquery-emulator:latest
    command:
      - "bigquery-emulator"
      - "--project=project"
      - "--dataset=dataset"
      - "--data-from-yaml=/data.yaml"
    ports:
      - "9050:9050"
    volumes:
      - ./hack/bigquery-emulator-data.yaml:/data.yaml

  dtrack-apiserver:
    profiles:
      - "dtrack"
    image: dependencytrack/apiserver:4.11.7
    ports:
      - "9010:8080"
    environment:
      - LOGGING_LEVEL=INFO
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080 || exit 1
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 10s
    volumes:
      - "dependency-track:/data"

  dtrack-frontend:
    profiles:
      - "dtrack"
    image: dependencytrack/frontend:4.11.7
    depends_on:
      - dtrack-apiserver
    environment:
      - API_BASE_URL=http://localhost:9010
    ports:
      - "9020:8080"

  bootstrap:
    profiles:
      - "dtrack"
    platform: linux/x86_64
    image: europe-north1-docker.pkg.dev/nais-io/nais/images/dependencytrack:2024-06-05-123815-24637f8
    environment:
      - LOG_LEVEL=debug
      - BASE_URL=http://dtrack-apiserver:8080/
      - DEFAULT_ADMIN_PASSWORD=admin
      - ADMIN_PASSWORD=yolo
      - USERS_FILE=/app/users.yaml
    volumes:
      - type: bind
        source: ./data/bootstrap/users.yaml
        target: /app/users.yaml
    depends_on:
      dtrack-apiserver:
        condition: service_healthy

volumes:
  pgdata:
  dependency-track:
