// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gengql

import (
	"context"
	"errors"
	"math"
	"strconv"
	"sync/atomic"
	"time"

	"github.com/99designs/gqlgen/graphql"
	"github.com/nais/api/internal/metrics"
	"github.com/vektah/gqlparser/v2/ast"
)

// region    ************************** generated!.gotpl **************************

// endregion ************************** generated!.gotpl **************************

// region    ***************************** args.gotpl *****************************

// endregion ***************************** args.gotpl *****************************

// region    ************************** directives.gotpl **************************

// endregion ************************** directives.gotpl **************************

// region    **************************** field.gotpl *****************************

func (ec *executionContext) _MetricLabel_name(ctx context.Context, field graphql.CollectedField, obj *metrics.MetricLabel) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_MetricLabel_name(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return obj.Name, nil
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v string) graphql.Marshaler {
			return ec.marshalNString2string(ctx, selections, v)
		},
		true,
		true,
	)
}
func (ec *executionContext) fieldContext_MetricLabel_name(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	return graphql.NewScalarFieldContext("MetricLabel", field, false, false, errors.New("field of type String does not have child fields"))
}

func (ec *executionContext) _MetricLabel_value(ctx context.Context, field graphql.CollectedField, obj *metrics.MetricLabel) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_MetricLabel_value(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return obj.Value, nil
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v string) graphql.Marshaler {
			return ec.marshalNString2string(ctx, selections, v)
		},
		true,
		true,
	)
}
func (ec *executionContext) fieldContext_MetricLabel_value(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	return graphql.NewScalarFieldContext("MetricLabel", field, false, false, errors.New("field of type String does not have child fields"))
}

func (ec *executionContext) _MetricSeries_labels(ctx context.Context, field graphql.CollectedField, obj *metrics.MetricSeries) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_MetricSeries_labels(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return obj.Labels, nil
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v []*metrics.MetricLabel) graphql.Marshaler {
			return ec.marshalNMetricLabel2ᚕᚖgithubᚗcomᚋnaisᚋapiᚋinternalᚋmetricsᚐMetricLabelᚄ(ctx, selections, v)
		},
		true,
		true,
	)
}
func (ec *executionContext) fieldContext_MetricSeries_labels(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "MetricSeries",
		Field:      field,
		IsMethod:   false,
		IsResolver: false,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.childFields_MetricLabel(ctx, field)
		},
	}
	return fc, nil
}

func (ec *executionContext) _MetricSeries_values(ctx context.Context, field graphql.CollectedField, obj *metrics.MetricSeries) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_MetricSeries_values(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return obj.Values, nil
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v []*metrics.MetricValue) graphql.Marshaler {
			return ec.marshalNMetricValue2ᚕᚖgithubᚗcomᚋnaisᚋapiᚋinternalᚋmetricsᚐMetricValueᚄ(ctx, selections, v)
		},
		true,
		true,
	)
}
func (ec *executionContext) fieldContext_MetricSeries_values(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "MetricSeries",
		Field:      field,
		IsMethod:   false,
		IsResolver: false,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.childFields_MetricValue(ctx, field)
		},
	}
	return fc, nil
}

func (ec *executionContext) _MetricValue_timestamp(ctx context.Context, field graphql.CollectedField, obj *metrics.MetricValue) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_MetricValue_timestamp(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return obj.Timestamp, nil
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v time.Time) graphql.Marshaler {
			return ec.marshalNTime2timeᚐTime(ctx, selections, v)
		},
		true,
		true,
	)
}
func (ec *executionContext) fieldContext_MetricValue_timestamp(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	return graphql.NewScalarFieldContext("MetricValue", field, false, false, errors.New("field of type Time does not have child fields"))
}

func (ec *executionContext) _MetricValue_value(ctx context.Context, field graphql.CollectedField, obj *metrics.MetricValue) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_MetricValue_value(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return obj.Value, nil
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v float64) graphql.Marshaler {
			return ec.marshalNFloat2float64(ctx, selections, v)
		},
		true,
		true,
	)
}
func (ec *executionContext) fieldContext_MetricValue_value(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	return graphql.NewScalarFieldContext("MetricValue", field, false, false, errors.New("field of type Float does not have child fields"))
}

func (ec *executionContext) _MetricsQueryResult_series(ctx context.Context, field graphql.CollectedField, obj *metrics.MetricsQueryResult) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_MetricsQueryResult_series(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return obj.Series, nil
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v []*metrics.MetricSeries) graphql.Marshaler {
			return ec.marshalNMetricSeries2ᚕᚖgithubᚗcomᚋnaisᚋapiᚋinternalᚋmetricsᚐMetricSeriesᚄ(ctx, selections, v)
		},
		true,
		true,
	)
}
func (ec *executionContext) fieldContext_MetricsQueryResult_series(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "MetricsQueryResult",
		Field:      field,
		IsMethod:   false,
		IsResolver: false,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.childFields_MetricSeries(ctx, field)
		},
	}
	return fc, nil
}

func (ec *executionContext) _MetricsQueryResult_warnings(ctx context.Context, field graphql.CollectedField, obj *metrics.MetricsQueryResult) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_MetricsQueryResult_warnings(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return obj.Warnings, nil
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v []string) graphql.Marshaler {
			return ec.marshalNString2ᚕstringᚄ(ctx, selections, v)
		},
		true,
		true,
	)
}
func (ec *executionContext) fieldContext_MetricsQueryResult_warnings(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	return graphql.NewScalarFieldContext("MetricsQueryResult", field, false, false, errors.New("field of type String does not have child fields"))
}

// endregion **************************** field.gotpl *****************************

// region    **************************** input.gotpl *****************************

func (ec *executionContext) unmarshalInputMetricsQueryInput(ctx context.Context, obj any) (metrics.MetricsQueryInput, error) {
	var it metrics.MetricsQueryInput
	if obj == nil {
		return it, nil
	}

	asMap := map[string]any{}
	for k, v := range obj.(map[string]any) {
		asMap[k] = v
	}

	fieldsInOrder := [...]string{"query", "time", "range"}
	for _, k := range fieldsInOrder {
		v, ok := asMap[k]
		if !ok {
			continue
		}
		switch k {
		case "query":
			ctx := graphql.WithPathContext(ctx, graphql.NewPathWithField("query"))
			data, err := ec.unmarshalNString2string(ctx, v)
			if err != nil {
				return it, err
			}
			it.Query = data
		case "time":
			ctx := graphql.WithPathContext(ctx, graphql.NewPathWithField("time"))
			data, err := ec.unmarshalOTime2ᚖtimeᚐTime(ctx, v)
			if err != nil {
				return it, err
			}
			it.Time = data
		case "range":
			ctx := graphql.WithPathContext(ctx, graphql.NewPathWithField("range"))
			data, err := ec.unmarshalOMetricsRangeInput2ᚖgithubᚗcomᚋnaisᚋapiᚋinternalᚋmetricsᚐMetricsRangeInput(ctx, v)
			if err != nil {
				return it, err
			}
			it.Range = data
		}
	}
	return it, nil
}

func (ec *executionContext) unmarshalInputMetricsRangeInput(ctx context.Context, obj any) (metrics.MetricsRangeInput, error) {
	var it metrics.MetricsRangeInput
	if obj == nil {
		return it, nil
	}

	asMap := map[string]any{}
	for k, v := range obj.(map[string]any) {
		asMap[k] = v
	}

	fieldsInOrder := [...]string{"start", "end", "step"}
	for _, k := range fieldsInOrder {
		v, ok := asMap[k]
		if !ok {
			continue
		}
		switch k {
		case "start":
			ctx := graphql.WithPathContext(ctx, graphql.NewPathWithField("start"))
			data, err := ec.unmarshalNTime2timeᚐTime(ctx, v)
			if err != nil {
				return it, err
			}
			it.Start = data
		case "end":
			ctx := graphql.WithPathContext(ctx, graphql.NewPathWithField("end"))
			data, err := ec.unmarshalNTime2timeᚐTime(ctx, v)
			if err != nil {
				return it, err
			}
			it.End = data
		case "step":
			ctx := graphql.WithPathContext(ctx, graphql.NewPathWithField("step"))
			data, err := ec.unmarshalNInt2int(ctx, v)
			if err != nil {
				return it, err
			}
			it.Step = data
		}
	}
	return it, nil
}

// endregion **************************** input.gotpl *****************************

// region    ************************** interface.gotpl ***************************

// endregion ************************** interface.gotpl ***************************

// region    **************************** object.gotpl ****************************

var metricLabelImplementors = []string{"MetricLabel"}

func (ec *executionContext) _MetricLabel(ctx context.Context, sel ast.SelectionSet, obj *metrics.MetricLabel) graphql.Marshaler {
	fields := graphql.CollectFields(ec.OperationContext, sel, metricLabelImplementors)

	out := graphql.NewFieldSet(fields)
	deferred := make(map[string]*graphql.FieldSet)
	for i, field := range fields {
		switch field.Name {
		case "__typename":
			out.Values[i] = graphql.MarshalString("MetricLabel")
		case "name":
			out.Values[i] = ec._MetricLabel_name(ctx, field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		case "value":
			out.Values[i] = ec._MetricLabel_value(ctx, field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		default:
			panic("unknown field " + strconv.Quote(field.Name))
		}
	}
	out.Dispatch(ctx)
	if out.Invalids > 0 {
		return graphql.Null
	}

	atomic.AddInt32(&ec.Deferred, int32(min(len(deferred), math.MaxInt32)))

	for label, dfs := range deferred {
		ec.ProcessDeferredGroup(graphql.DeferredGroup{
			Label:    label,
			Path:     graphql.GetPath(ctx),
			FieldSet: dfs,
			Context:  ctx,
		})
	}

	return out
}

var metricSeriesImplementors = []string{"MetricSeries"}

func (ec *executionContext) _MetricSeries(ctx context.Context, sel ast.SelectionSet, obj *metrics.MetricSeries) graphql.Marshaler {
	fields := graphql.CollectFields(ec.OperationContext, sel, metricSeriesImplementors)

	out := graphql.NewFieldSet(fields)
	deferred := make(map[string]*graphql.FieldSet)
	for i, field := range fields {
		switch field.Name {
		case "__typename":
			out.Values[i] = graphql.MarshalString("MetricSeries")
		case "labels":
			out.Values[i] = ec._MetricSeries_labels(ctx, field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		case "values":
			out.Values[i] = ec._MetricSeries_values(ctx, field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		default:
			panic("unknown field " + strconv.Quote(field.Name))
		}
	}
	out.Dispatch(ctx)
	if out.Invalids > 0 {
		return graphql.Null
	}

	atomic.AddInt32(&ec.Deferred, int32(min(len(deferred), math.MaxInt32)))

	for label, dfs := range deferred {
		ec.ProcessDeferredGroup(graphql.DeferredGroup{
			Label:    label,
			Path:     graphql.GetPath(ctx),
			FieldSet: dfs,
			Context:  ctx,
		})
	}

	return out
}

var metricValueImplementors = []string{"MetricValue"}

func (ec *executionContext) _MetricValue(ctx context.Context, sel ast.SelectionSet, obj *metrics.MetricValue) graphql.Marshaler {
	fields := graphql.CollectFields(ec.OperationContext, sel, metricValueImplementors)

	out := graphql.NewFieldSet(fields)
	deferred := make(map[string]*graphql.FieldSet)
	for i, field := range fields {
		switch field.Name {
		case "__typename":
			out.Values[i] = graphql.MarshalString("MetricValue")
		case "timestamp":
			out.Values[i] = ec._MetricValue_timestamp(ctx, field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		case "value":
			out.Values[i] = ec._MetricValue_value(ctx, field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		default:
			panic("unknown field " + strconv.Quote(field.Name))
		}
	}
	out.Dispatch(ctx)
	if out.Invalids > 0 {
		return graphql.Null
	}

	atomic.AddInt32(&ec.Deferred, int32(min(len(deferred), math.MaxInt32)))

	for label, dfs := range deferred {
		ec.ProcessDeferredGroup(graphql.DeferredGroup{
			Label:    label,
			Path:     graphql.GetPath(ctx),
			FieldSet: dfs,
			Context:  ctx,
		})
	}

	return out
}

var metricsQueryResultImplementors = []string{"MetricsQueryResult"}

func (ec *executionContext) _MetricsQueryResult(ctx context.Context, sel ast.SelectionSet, obj *metrics.MetricsQueryResult) graphql.Marshaler {
	fields := graphql.CollectFields(ec.OperationContext, sel, metricsQueryResultImplementors)

	out := graphql.NewFieldSet(fields)
	deferred := make(map[string]*graphql.FieldSet)
	for i, field := range fields {
		switch field.Name {
		case "__typename":
			out.Values[i] = graphql.MarshalString("MetricsQueryResult")
		case "series":
			out.Values[i] = ec._MetricsQueryResult_series(ctx, field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		case "warnings":
			out.Values[i] = ec._MetricsQueryResult_warnings(ctx, field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		default:
			panic("unknown field " + strconv.Quote(field.Name))
		}
	}
	out.Dispatch(ctx)
	if out.Invalids > 0 {
		return graphql.Null
	}

	atomic.AddInt32(&ec.Deferred, int32(min(len(deferred), math.MaxInt32)))

	for label, dfs := range deferred {
		ec.ProcessDeferredGroup(graphql.DeferredGroup{
			Label:    label,
			Path:     graphql.GetPath(ctx),
			FieldSet: dfs,
			Context:  ctx,
		})
	}

	return out
}

// endregion **************************** object.gotpl ****************************

// region    ***************************** type.gotpl *****************************

func (ec *executionContext) marshalNMetricLabel2ᚕᚖgithubᚗcomᚋnaisᚋapiᚋinternalᚋmetricsᚐMetricLabelᚄ(ctx context.Context, sel ast.SelectionSet, v []*metrics.MetricLabel) graphql.Marshaler {
	ret := graphql.MarshalSliceConcurrently(ctx, len(v), 0, false, func(ctx context.Context, i int) graphql.Marshaler {
		fc := graphql.GetFieldContext(ctx)
		fc.Result = &v[i]
		return ec.marshalNMetricLabel2ᚖgithubᚗcomᚋnaisᚋapiᚋinternalᚋmetricsᚐMetricLabel(ctx, sel, v[i])
	})

	for _, e := range ret {
		if e == graphql.Null {
			return graphql.Null
		}
	}

	return ret
}

func (ec *executionContext) marshalNMetricLabel2ᚖgithubᚗcomᚋnaisᚋapiᚋinternalᚋmetricsᚐMetricLabel(ctx context.Context, sel ast.SelectionSet, v *metrics.MetricLabel) graphql.Marshaler {
	if v == nil {
		if !graphql.HasFieldError(ctx, graphql.GetFieldContext(ctx)) {
			graphql.AddErrorf(ctx, "the requested element is null which the schema does not allow")
		}
		return graphql.Null
	}
	return ec._MetricLabel(ctx, sel, v)
}

func (ec *executionContext) marshalNMetricSeries2ᚕᚖgithubᚗcomᚋnaisᚋapiᚋinternalᚋmetricsᚐMetricSeriesᚄ(ctx context.Context, sel ast.SelectionSet, v []*metrics.MetricSeries) graphql.Marshaler {
	ret := graphql.MarshalSliceConcurrently(ctx, len(v), 0, false, func(ctx context.Context, i int) graphql.Marshaler {
		fc := graphql.GetFieldContext(ctx)
		fc.Result = &v[i]
		return ec.marshalNMetricSeries2ᚖgithubᚗcomᚋnaisᚋapiᚋinternalᚋmetricsᚐMetricSeries(ctx, sel, v[i])
	})

	for _, e := range ret {
		if e == graphql.Null {
			return graphql.Null
		}
	}

	return ret
}

func (ec *executionContext) marshalNMetricSeries2ᚖgithubᚗcomᚋnaisᚋapiᚋinternalᚋmetricsᚐMetricSeries(ctx context.Context, sel ast.SelectionSet, v *metrics.MetricSeries) graphql.Marshaler {
	if v == nil {
		if !graphql.HasFieldError(ctx, graphql.GetFieldContext(ctx)) {
			graphql.AddErrorf(ctx, "the requested element is null which the schema does not allow")
		}
		return graphql.Null
	}
	return ec._MetricSeries(ctx, sel, v)
}

func (ec *executionContext) marshalNMetricValue2ᚕᚖgithubᚗcomᚋnaisᚋapiᚋinternalᚋmetricsᚐMetricValueᚄ(ctx context.Context, sel ast.SelectionSet, v []*metrics.MetricValue) graphql.Marshaler {
	ret := graphql.MarshalSliceConcurrently(ctx, len(v), 0, false, func(ctx context.Context, i int) graphql.Marshaler {
		fc := graphql.GetFieldContext(ctx)
		fc.Result = &v[i]
		return ec.marshalNMetricValue2ᚖgithubᚗcomᚋnaisᚋapiᚋinternalᚋmetricsᚐMetricValue(ctx, sel, v[i])
	})

	for _, e := range ret {
		if e == graphql.Null {
			return graphql.Null
		}
	}

	return ret
}

func (ec *executionContext) marshalNMetricValue2ᚖgithubᚗcomᚋnaisᚋapiᚋinternalᚋmetricsᚐMetricValue(ctx context.Context, sel ast.SelectionSet, v *metrics.MetricValue) graphql.Marshaler {
	if v == nil {
		if !graphql.HasFieldError(ctx, graphql.GetFieldContext(ctx)) {
			graphql.AddErrorf(ctx, "the requested element is null which the schema does not allow")
		}
		return graphql.Null
	}
	return ec._MetricValue(ctx, sel, v)
}

func (ec *executionContext) unmarshalNMetricsQueryInput2githubᚗcomᚋnaisᚋapiᚋinternalᚋmetricsᚐMetricsQueryInput(ctx context.Context, v any) (metrics.MetricsQueryInput, error) {
	res, err := ec.unmarshalInputMetricsQueryInput(ctx, v)
	return res, graphql.ErrorOnPath(ctx, err)
}

func (ec *executionContext) marshalNMetricsQueryResult2githubᚗcomᚋnaisᚋapiᚋinternalᚋmetricsᚐMetricsQueryResult(ctx context.Context, sel ast.SelectionSet, v metrics.MetricsQueryResult) graphql.Marshaler {
	return ec._MetricsQueryResult(ctx, sel, &v)
}

func (ec *executionContext) marshalNMetricsQueryResult2ᚖgithubᚗcomᚋnaisᚋapiᚋinternalᚋmetricsᚐMetricsQueryResult(ctx context.Context, sel ast.SelectionSet, v *metrics.MetricsQueryResult) graphql.Marshaler {
	if v == nil {
		if !graphql.HasFieldError(ctx, graphql.GetFieldContext(ctx)) {
			graphql.AddErrorf(ctx, "the requested element is null which the schema does not allow")
		}
		return graphql.Null
	}
	return ec._MetricsQueryResult(ctx, sel, v)
}

func (ec *executionContext) unmarshalOMetricsRangeInput2ᚖgithubᚗcomᚋnaisᚋapiᚋinternalᚋmetricsᚐMetricsRangeInput(ctx context.Context, v any) (*metrics.MetricsRangeInput, error) {
	if v == nil {
		return nil, nil
	}
	res, err := ec.unmarshalInputMetricsRangeInput(ctx, v)
	return &res, graphql.ErrorOnPath(ctx, err)
}

// endregion ***************************** type.gotpl *****************************
