apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: deprecated-registry
spec:
  image: navikt/app-name:latest
  replicas:
    min: 2
    max: 2

---
apiVersion: v1
kind: Pod
metadata:
  name: deprecated-registry-1
  labels:
    app: deprecated-registry
  creationTimestamp: "2021-09-30T12:00:00Z"
spec:
  containers:
    - name: deprecated-registry
      image: europe-north1-docker.pkg.dev/nais/navikt/app-name:latest
status:
  containerStatuses:
    - name: deprecated-registry
      ready: true
      restartCount: 0
