apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: invalid-yaml
spec:
  image: europe-north1-docker.pkg.dev/nais/navikt/app-name:latest
  replicas:
    min: 2
    max: 2
status:
  conditions:
    - type: "SynchronizationState"
      reason: "FailedGenerate"
      message: "Human text from the operator, received from yaml"

---
apiVersion: v1
kind: Pod
metadata:
  name: invalid-yaml-1
  labels:
    app: invalid-yaml
  creationTimestamp: "2021-09-30T12:00:00Z"
spec:
  containers:
    - name: invalid-yaml
      image: europe-north1-docker.pkg.dev/nais/navikt/app-name:latest
status:
  containerStatuses:
    - name: invalid-yaml
      ready: true
      restartCount: 0
