apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: invalid-yaml
spec:
  image: europe-north1-docker.pkg.dev/nais/navikt/app-name:latest
  schedule: "0 0 * * *"
status:
  conditions:
    - type: "SynchronizationState"
      reason: "FailedGenerate"
      message: "Human text from the operator, received from yaml"

---
apiVersion: batch/v1
kind: Job
metadata:
  name: invalid-yaml
  labels:
    app: invalid-yaml
spec:
  template:
    spec:
      containers:
        - name: invalid-yaml
          image: europe-north1-docker.pkg.dev/nais/navikt/app-name:latest
status:
  failed: 0
