apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: failed-synchronization
spec:
  image: europe-north1-docker.pkg.dev/nais/navikt/app-name:latest
  schedule: "0 0 * * *"
status:
  conditions:
    - type: "SynchronizationState"
      reason: "FailedSynchronization"
      message: "Human text from the operator, received from yaml"

---
apiVersion: batch/v1
kind: Job
metadata:
  name: failed-synchronization
  labels:
    app: failed-synchronization
spec:
  template:
    spec:
      containers:
        - name: failed-synchronization
          image: europe-north1-docker.pkg.dev/nais/navikt/app-name:latest
status:
  failed: 0
