apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: app
spec:
  image: navikt/app-name:latest
  ingresses:
    - "https://another-app.external.server.com"
  replicas:
    max: 1
    min: 1
