// Code generated by sqlc. DO NOT EDIT.
// source: audit_events.sql

package gensql

import (
	"context"

	"github.com/nais/api/internal/slug"
)

const createAuditEvent = `-- name: CreateAuditEvent :exec
INSERT INTO audit_events (actor, action, resource_type, resource_name, team_slug, environment, data)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateAuditEventParams struct {
	Actor        string
	Action       string
	ResourceType string
	ResourceName string
	Team         *slug.Slug
	Environment  *string
	Data         []byte
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) error {
	_, err := q.db.Exec(ctx, createAuditEvent,
		arg.Actor,
		arg.Action,
		arg.ResourceType,
		arg.ResourceName,
		arg.Team,
		arg.Environment,
		arg.Data,
	)
	return err
}

const getAuditEventsCountForTeam = `-- name: GetAuditEventsCountForTeam :one
SELECT COUNT(*) FROM audit_events
WHERE team_slug = $1
`

func (q *Queries) GetAuditEventsCountForTeam(ctx context.Context, team *slug.Slug) (int64, error) {
	row := q.db.QueryRow(ctx, getAuditEventsCountForTeam, team)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAuditEventsCountForTeamByResource = `-- name: GetAuditEventsCountForTeamByResource :one
SELECT COUNT(*) FROM audit_events
WHERE team_slug = $1
AND resource_type = $2
`

type GetAuditEventsCountForTeamByResourceParams struct {
	Team         *slug.Slug
	ResourceType string
}

func (q *Queries) GetAuditEventsCountForTeamByResource(ctx context.Context, arg GetAuditEventsCountForTeamByResourceParams) (int64, error) {
	row := q.db.QueryRow(ctx, getAuditEventsCountForTeamByResource, arg.Team, arg.ResourceType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAuditEventsForTeam = `-- name: GetAuditEventsForTeam :many
SELECT id, created_at, actor, action, resource_type, resource_name, team_slug, data, environment FROM audit_events
WHERE team_slug = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type GetAuditEventsForTeamParams struct {
	Team   *slug.Slug
	Offset int32
	Limit  int32
}

func (q *Queries) GetAuditEventsForTeam(ctx context.Context, arg GetAuditEventsForTeamParams) ([]*AuditEvent, error) {
	rows, err := q.db.Query(ctx, getAuditEventsForTeam, arg.Team, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Actor,
			&i.Action,
			&i.ResourceType,
			&i.ResourceName,
			&i.TeamSlug,
			&i.Data,
			&i.Environment,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuditEventsForTeamByResource = `-- name: GetAuditEventsForTeamByResource :many
SELECT id, created_at, actor, action, resource_type, resource_name, team_slug, data, environment FROM audit_events
WHERE
    team_slug = $1
    AND resource_type = $2
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type GetAuditEventsForTeamByResourceParams struct {
	Team         *slug.Slug
	ResourceType string
	Offset       int32
	Limit        int32
}

func (q *Queries) GetAuditEventsForTeamByResource(ctx context.Context, arg GetAuditEventsForTeamByResourceParams) ([]*AuditEvent, error) {
	rows, err := q.db.Query(ctx, getAuditEventsForTeamByResource,
		arg.Team,
		arg.ResourceType,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Actor,
			&i.Action,
			&i.ResourceType,
			&i.ResourceName,
			&i.TeamSlug,
			&i.Data,
			&i.Environment,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
