apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app: "{{ .Release.Name }}"
spec:
  ingressClassName: "{{ .Values.ingressClassName }}"
  rules:
    - host: "{{ .Values.host }}"
      http:
        paths:
          - backend:
              service:
                name: "{{ .Release.Name }}"
                port:
                  name: http
            path: /query
            pathType: Prefix
          - backend:
              service:
                name: "{{ .Release.Name }}"
                port:
                  name: http
            path: /oauth2/
            pathType: Prefix
