apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app: "{{ .Release.Name }}"
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Robots-Tag: noindex";
spec:
  ingressClassName: "{{ .Values.ingressClassName }}"
  rules:
    - host: "{{ .Values.host }}"
      http:
        paths:
          - backend:
              service:
                name: "{{ .Release.Name }}"
                port:
                  name: http
            path: /graphql
            pathType: Prefix
          - backend:
              service:
                name: "{{ .Release.Name }}"
                port:
                  name: http
            path: /oauth2/
            pathType: Prefix
