apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Release.Name }}-lease"
  labels:
    app: "{{ .Release.Name }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ .Release.Name }}-lease"
subjects:
  - kind: ServiceAccount
    name: "{{ .Release.Name }}"
    namespace: "{{ .Release.Namespace }}"
