apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app: "{{ .Release.Name }}"
spec:
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
    - to:
        - ipBlock:
            cidr: {{ .Values.apiserverIP }}/32
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: loki
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: hookd
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: v13s
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: bifrost
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: "{{ .Release.Namespace }}"
  podSelector:
    matchLabels:
      app: "{{ .Release.Name }}"
  policyTypes:
    - Egress
    - Ingress
