apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: "{{ .Release.Name }}"
  namespace: nais-system
  labels:
    app: "{{ .Release.Name }}"
spec:
  podMetricsEndpoints:
    - interval: 1m
      port: metrics
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - nais-system
  selector:
    matchLabels:
      app: "{{ .Release.Name }}"
