apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ .Release.Name }}-unleash-admin"
  namespace: {{ .Values.unleash.namespace }}
  labels:
    app: "{{ .Release.Name }}"
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - secrets/status
      - events
      - pods
      - pods/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - unleash.nais.io
    resources:
      - unleashes
    verbs:
      - "*"
  - apiGroups:
      - networking.gke.io
    resources:
      - fqdnnetworkpolicies
    verbs:
      - "*"
