{{if .Values.unleash.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Release.Name }}-unleash-admin"
  namespace: {{ .Values.unleash.namespace }}
  labels:
    app: "{{ .Release.Name }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ .Release.Name }}-unleash-admin"
subjects:
  - kind: ServiceAccount
    name: "{{ .Release.Name }}"
    namespace: {{ .Release.Namespace }}
{{ end }}
