#!/usr/bin/env sh
#MISE description="Setup local development environment"

set -e

GOOGLE_MANAGEMENT_PROJECT_ID=nais-local-dev go run ./cmd/setup_local -users 40 -teams 10 -owners 2 -members 4 -provision_pub_sub
