apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: jobname-1
spec:
  image: europe-north1-docker.pkg.dev/nais/navikt/app-name:latest
  schedule: "0 0 * * *"

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: jobname-1
  labels:
    app: jobname-1
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    metadata:
      labels:
        app: jobname-1
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: europe-north1-docker.pkg.dev/nais/navikt/app-name:latest
              command:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure

---
apiVersion: batch/v1
kind: Job
metadata:
  name: jobname-1-run1
  labels:
    app: jobname-1
spec:
  template:
    spec:
      containers:
        - name: jobname-1
          image: europe-north1-docker.pkg.dev/nais/navikt/app-name:latest
status:
  failed: 0
