---
apiVersion: aiven.io/v1alpha1
kind: OpenSearch
metadata:
  annotations:
    controllers.aiven.io/generation-was-processed: "2"
    controllers.aiven.io/instance-is-running: "true"
  labels:
    app: app-name
  name: opensearch-slug-1-opensearch
spec:
  cloudName: google-europe-north1
  connInfoSecretTarget:
    name: ""
  disk_space: 525G
  plan: business-8
  project: nav-dev
  projectVpcId: fff21e17-95d5-408b-8df5-15aacf38f5de
  tags:
    environment: dev
    team: slug-1
    tenant: nav
  terminationProtection: true
  userConfig:
    opensearch_version: "2"
status:
  conditions:
    - lastTransitionTime: "2023-11-08T10:36:06Z"
      message: Instance was created or update on Aiven side
      reason: Updated
      status: "True"
      type: Initialized
    - lastTransitionTime: "2024-01-10T09:40:58Z"
      message: Instance is running on Aiven side
      reason: CheckRunning
      status: "True"
      type: Running
  state: RUNNING
