apiVersion: nais.io/v1
kind: Postgres
metadata:
  name: existing
  namespace: pg-crud-team
spec:
  majorVersion: "17"
  highAvailability: false
  resources:
    cpu: 100m
    memory: 512Mi
    diskSize: 10Gi
---
apiVersion: nais.io/v1
kind: PostgresBranch
metadata:
  name: existing-main-f68e5aa4
  namespace: pg-crud-team
spec:
  postgres: existing
  branchName: main
status:
  reconcilePhase: Completed
  conditions:
    - type: cluster.postgresql.cnpg.io/ObservedState
      status: "True"
      reason: Reconciled
      message: "Cluster is in phase: Cluster in healthy state"
      lastTransitionTime: "2026-09-17T00:00:00Z"
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-existing-main-f68e5aa4
  namespace: pg-crud-team
status:
  conditions:
    - type: Ready
      status: "True"
