---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: app-one
  namespace: labelteam
  labels:
    tag: target
    priority: high
spec:
  image: navikt/app-one:latest
---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: app-two
  namespace: labelteam
  labels:
    tag: target
spec:
  image: navikt/app-two:latest
---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: app-three
  namespace: labelteam
  labels:
    tag: other
spec:
  image: navikt/app-three:latest
