---
apiVersion: data.nais.io/v1
kind: Postgres
metadata:
  name: postgres-one
  namespace: labelteam
  labels:
    labels.nais.io/tag: target
    labels.nais.io/priority: high
spec:
  cluster:
    majorVersion: "17"
    resources:
      cpu: 100m
      diskSize: 2Gi
      memory: 2G
  database:
    collation: nb_NO
---
apiVersion: data.nais.io/v1
kind: Postgres
metadata:
  name: postgres-two
  namespace: labelteam
  labels:
    labels.nais.io/tag: target
spec:
  cluster:
    majorVersion: "17"
    resources:
      cpu: 100m
      diskSize: 2Gi
      memory: 2G
  database:
    collation: nb_NO
---
apiVersion: data.nais.io/v1
kind: Postgres
metadata:
  name: postgres-three
  namespace: labelteam
  labels:
    labels.nais.io/tag: other
spec:
  cluster:
    majorVersion: "17"
    resources:
      cpu: 100m
      diskSize: 2Gi
      memory: 2G
  database:
    collation: nb_NO
