---
apiVersion: aiven.io/v1alpha1
kind: Valkey
metadata:
  name: valkey-one
  namespace: labelteam
  labels:
    labels.nais.io/tag: target
    labels.nais.io/priority: high
spec:
  plan: startup-4
---
apiVersion: aiven.io/v1alpha1
kind: Valkey
metadata:
  name: valkey-two
  namespace: labelteam
  labels:
    labels.nais.io/tag: target
spec:
  plan: startup-4
---
apiVersion: aiven.io/v1alpha1
kind: Valkey
metadata:
  name: valkey-three
  namespace: labelteam
  labels:
    labels.nais.io/tag: other
spec:
  plan: startup-4
