apiserverIP:

auditLog:
  projectID: # mapped in fasit
  location: # must be configured

database: # mapped in fasit
  instance:
  name:
  user:
  password:

image:
  repository: europe-north1-docker.pkg.dev/nais-io/nais/images
  name: nais-api

  cloudsql_proxy: gcr.io/cloudsql-docker/gce-proxy:1.33.16

host: ""

hookd:
  psk: ""

v13s:
  endpoint: "v13s:3001"

serviceaccount:
  email: ""

fasit:
  tenant:
    name: "dev-nais"

kubernetes:
  clusters: "dev,prod"
  static: ""

resources:
  cpu: 300m
  memory: 512Mi

alerts:
  enabled: true

tenant:
  domain: example.com

google:
  managementProjectID: "" # mapped in fasit

oauth: # mapped in fasit
  issuer: "https://auth.nais.io"
  clientID: ""
  clientSecret: ""

slack:
  feedbackChannel: "console-user-feedback"
  token: "" # Config in fasit

staticServiceAccounts: "" # mapped in fasit

replaceEnvironmentNames: null # mapped in fasit

usersync:
  serviceAccount: null # Config in fasit
  subjectEmail: null # Config in fasit
  adminGroupPrefix: null # Config in fasit

unleash:
  enabled: false
  namespace: "bifrost-unleash"
  bifrostApiUrl: "http://bifrost-backend"

replicas: 2

logging:
  loki: false
  secure_logs: false

zitadel:
  domain:
  idpID:
  key:
  organizationID:

aiven:
  projects: {}
  token:
