apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: app-with-no-secrets
---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: app-with-secrets-via-envfrom
spec:
  envFrom:
    - secret: managed-secret-in-dev
