// Code generated by sqlc. DO NOT EDIT.

package issuesql

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetIssueByID(ctx context.Context, id uuid.UUID) (*Issue, error)
	ListIssues(ctx context.Context, arg ListIssuesParams) ([]*ListIssuesRow, error)
}

var _ Querier = (*Queries)(nil)
