apiVersion: nais.io/v1
kind: PostgresAccess
metadata:
  name: recovered-access
  namespace: someteamname
spec:
  postgresInstance: foobar-recovered
  username: user@usersen.com
  accessLevel: read
  expiresAt: "2099-09-17T12:00:00Z"
status:
  conditions:
    - type: Ready
      status: "False"
