apiVersion: nais.io/v1
kind: PostgresInstance
metadata:
  name: foobar-recovered
  namespace: someteamname
spec:
  postgres: foobar
status:
  reconcilePhase: Completed
  conditions:
    - type: cluster.postgresql.cnpg.io/ObservedState
      status: "True"
      reason: Reconciled
      message: "Cluster is in phase: Cluster in healthy state"
      lastTransitionTime: "2026-09-17T00:00:00Z"
