apiVersion: nais.io/v1alpha1
kind: RelayAccess
metadata:
  name: missing-secret-access
  namespace: someteamname
  ownerReferences:
    - apiVersion: nais.io/v1
      kind: PostgresAccess
      name: missing-secret-access
      uid: 22222222-2222-4222-8222-222222222222
      controller: true
spec:
  target:
    serviceName: pg-foobar-rw
    port: 5432
  expiresAt: "2099-09-17T12:00:00Z"
  tokenSHA256: 630dcd2966c4336691125448bbb25b4ff412a49c732db2c8abc1b8581bd710dd
