apiVersion: v1
kind: Secret
metadata:
  name: ready-access-credentials
  namespace: someteamname
type: kubernetes.io/basic-auth
data:
  username: YXBwLWZvb2Jhci1hYmMxMjM=
  password: c3VwZXJzZWNyZXQ=
  ca.crt: dGVzdC1jYS1jZXJ0aWZpY2F0ZQ==
