// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: databases.proto

package protoapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Databases_List_FullMethodName = "/nais.api.protobuf.Databases/List"
)

// DatabasesClient is the client API for Databases service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DatabasesClient interface {
	List(ctx context.Context, in *ListDatabasesRequest, opts ...grpc.CallOption) (*ListDatabasesResponse, error)
}

type databasesClient struct {
	cc grpc.ClientConnInterface
}

func NewDatabasesClient(cc grpc.ClientConnInterface) DatabasesClient {
	return &databasesClient{cc}
}

func (c *databasesClient) List(ctx context.Context, in *ListDatabasesRequest, opts ...grpc.CallOption) (*ListDatabasesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDatabasesResponse)
	err := c.cc.Invoke(ctx, Databases_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DatabasesServer is the server API for Databases service.
// All implementations must embed UnimplementedDatabasesServer
// for forward compatibility.
type DatabasesServer interface {
	List(context.Context, *ListDatabasesRequest) (*ListDatabasesResponse, error)
	mustEmbedUnimplementedDatabasesServer()
}

// UnimplementedDatabasesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDatabasesServer struct{}

func (UnimplementedDatabasesServer) List(context.Context, *ListDatabasesRequest) (*ListDatabasesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedDatabasesServer) mustEmbedUnimplementedDatabasesServer() {}
func (UnimplementedDatabasesServer) testEmbeddedByValue()                   {}

// UnsafeDatabasesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DatabasesServer will
// result in compilation errors.
type UnsafeDatabasesServer interface {
	mustEmbedUnimplementedDatabasesServer()
}

func RegisterDatabasesServer(s grpc.ServiceRegistrar, srv DatabasesServer) {
	// If the following call pancis, it indicates UnimplementedDatabasesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Databases_ServiceDesc, srv)
}

func _Databases_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDatabasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabasesServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Databases_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabasesServer).List(ctx, req.(*ListDatabasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Databases_ServiceDesc is the grpc.ServiceDesc for Databases service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Databases_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nais.api.protobuf.Databases",
	HandlerType: (*DatabasesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Databases_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "databases.proto",
}
