// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package protoapi

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockDatabasesServer creates a new instance of MockDatabasesServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDatabasesServer(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockDatabasesServer {
	mock := &MockDatabasesServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDatabasesServer is an autogenerated mock type for the DatabasesServer type
type MockDatabasesServer struct {
	mock.Mock
}

type MockDatabasesServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDatabasesServer) EXPECT() *MockDatabasesServer_Expecter {
	return &MockDatabasesServer_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type MockDatabasesServer
func (_mock *MockDatabasesServer) List(context1 context.Context, listDatabasesRequest *ListDatabasesRequest) (*ListDatabasesResponse, error) {
	ret := _mock.Called(context1, listDatabasesRequest)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *ListDatabasesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ListDatabasesRequest) (*ListDatabasesResponse, error)); ok {
		return returnFunc(context1, listDatabasesRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ListDatabasesRequest) *ListDatabasesResponse); ok {
		r0 = returnFunc(context1, listDatabasesRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ListDatabasesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ListDatabasesRequest) error); ok {
		r1 = returnFunc(context1, listDatabasesRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatabasesServer_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockDatabasesServer_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - context1 context.Context
//   - listDatabasesRequest *ListDatabasesRequest
func (_e *MockDatabasesServer_Expecter) List(context1 interface{}, listDatabasesRequest interface{}) *MockDatabasesServer_List_Call {
	return &MockDatabasesServer_List_Call{Call: _e.mock.On("List", context1, listDatabasesRequest)}
}

func (_c *MockDatabasesServer_List_Call) Run(run func(context1 context.Context, listDatabasesRequest *ListDatabasesRequest)) *MockDatabasesServer_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ListDatabasesRequest
		if args[1] != nil {
			arg1 = args[1].(*ListDatabasesRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatabasesServer_List_Call) Return(listDatabasesResponse *ListDatabasesResponse, err error) *MockDatabasesServer_List_Call {
	_c.Call.Return(listDatabasesResponse, err)
	return _c
}

func (_c *MockDatabasesServer_List_Call) RunAndReturn(run func(context1 context.Context, listDatabasesRequest *ListDatabasesRequest) (*ListDatabasesResponse, error)) *MockDatabasesServer_List_Call {
	_c.Call.Return(run)
	return _c
}

// mustEmbedUnimplementedDatabasesServer provides a mock function for the type MockDatabasesServer
func (_mock *MockDatabasesServer) mustEmbedUnimplementedDatabasesServer() {
	_mock.Called()
	return
}

// MockDatabasesServer_mustEmbedUnimplementedDatabasesServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedDatabasesServer'
type MockDatabasesServer_mustEmbedUnimplementedDatabasesServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedDatabasesServer is a helper method to define mock.On call
func (_e *MockDatabasesServer_Expecter) mustEmbedUnimplementedDatabasesServer() *MockDatabasesServer_mustEmbedUnimplementedDatabasesServer_Call {
	return &MockDatabasesServer_mustEmbedUnimplementedDatabasesServer_Call{Call: _e.mock.On("mustEmbedUnimplementedDatabasesServer")}
}

func (_c *MockDatabasesServer_mustEmbedUnimplementedDatabasesServer_Call) Run(run func()) *MockDatabasesServer_mustEmbedUnimplementedDatabasesServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDatabasesServer_mustEmbedUnimplementedDatabasesServer_Call) Return() *MockDatabasesServer_mustEmbedUnimplementedDatabasesServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDatabasesServer_mustEmbedUnimplementedDatabasesServer_Call) RunAndReturn(run func()) *MockDatabasesServer_mustEmbedUnimplementedDatabasesServer_Call {
	_c.Run(run)
	return _c
}
