// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.4
// source: reconcilers.proto

//go:build protoopaque

package protoapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SuccessfulTeamSyncRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TeamSlug string                 `protobuf:"bytes,1,opt,name=team_slug,json=teamSlug,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SuccessfulTeamSyncRequest) Reset() {
	*x = SuccessfulTeamSyncRequest{}
	mi := &file_reconcilers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuccessfulTeamSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessfulTeamSyncRequest) ProtoMessage() {}

func (x *SuccessfulTeamSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reconcilers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SuccessfulTeamSyncRequest) GetTeamSlug() string {
	if x != nil {
		return x.xxx_hidden_TeamSlug
	}
	return ""
}

func (x *SuccessfulTeamSyncRequest) SetTeamSlug(v string) {
	x.xxx_hidden_TeamSlug = v
}

type SuccessfulTeamSyncRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TeamSlug string
}

func (b0 SuccessfulTeamSyncRequest_builder) Build() *SuccessfulTeamSyncRequest {
	m0 := &SuccessfulTeamSyncRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TeamSlug = b.TeamSlug
	return m0
}

type SuccessfulTeamSyncResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuccessfulTeamSyncResponse) Reset() {
	*x = SuccessfulTeamSyncResponse{}
	mi := &file_reconcilers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuccessfulTeamSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessfulTeamSyncResponse) ProtoMessage() {}

func (x *SuccessfulTeamSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reconcilers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type SuccessfulTeamSyncResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 SuccessfulTeamSyncResponse_builder) Build() *SuccessfulTeamSyncResponse {
	m0 := &SuccessfulTeamSyncResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type SetReconcilerErrorForTeamRequest struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TeamSlug       string                 `protobuf:"bytes,1,opt,name=team_slug,json=teamSlug,proto3"`
	xxx_hidden_ReconcilerName string                 `protobuf:"bytes,2,opt,name=reconciler_name,json=reconcilerName,proto3"`
	xxx_hidden_CorrelationId  string                 `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3"`
	xxx_hidden_ErrorMessage   string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *SetReconcilerErrorForTeamRequest) Reset() {
	*x = SetReconcilerErrorForTeamRequest{}
	mi := &file_reconcilers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetReconcilerErrorForTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetReconcilerErrorForTeamRequest) ProtoMessage() {}

func (x *SetReconcilerErrorForTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reconcilers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SetReconcilerErrorForTeamRequest) GetTeamSlug() string {
	if x != nil {
		return x.xxx_hidden_TeamSlug
	}
	return ""
}

func (x *SetReconcilerErrorForTeamRequest) GetReconcilerName() string {
	if x != nil {
		return x.xxx_hidden_ReconcilerName
	}
	return ""
}

func (x *SetReconcilerErrorForTeamRequest) GetCorrelationId() string {
	if x != nil {
		return x.xxx_hidden_CorrelationId
	}
	return ""
}

func (x *SetReconcilerErrorForTeamRequest) GetErrorMessage() string {
	if x != nil {
		return x.xxx_hidden_ErrorMessage
	}
	return ""
}

func (x *SetReconcilerErrorForTeamRequest) SetTeamSlug(v string) {
	x.xxx_hidden_TeamSlug = v
}

func (x *SetReconcilerErrorForTeamRequest) SetReconcilerName(v string) {
	x.xxx_hidden_ReconcilerName = v
}

func (x *SetReconcilerErrorForTeamRequest) SetCorrelationId(v string) {
	x.xxx_hidden_CorrelationId = v
}

func (x *SetReconcilerErrorForTeamRequest) SetErrorMessage(v string) {
	x.xxx_hidden_ErrorMessage = v
}

type SetReconcilerErrorForTeamRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TeamSlug       string
	ReconcilerName string
	CorrelationId  string
	ErrorMessage   string
}

func (b0 SetReconcilerErrorForTeamRequest_builder) Build() *SetReconcilerErrorForTeamRequest {
	m0 := &SetReconcilerErrorForTeamRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TeamSlug = b.TeamSlug
	x.xxx_hidden_ReconcilerName = b.ReconcilerName
	x.xxx_hidden_CorrelationId = b.CorrelationId
	x.xxx_hidden_ErrorMessage = b.ErrorMessage
	return m0
}

type SetReconcilerErrorForTeamResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetReconcilerErrorForTeamResponse) Reset() {
	*x = SetReconcilerErrorForTeamResponse{}
	mi := &file_reconcilers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetReconcilerErrorForTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetReconcilerErrorForTeamResponse) ProtoMessage() {}

func (x *SetReconcilerErrorForTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reconcilers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type SetReconcilerErrorForTeamResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 SetReconcilerErrorForTeamResponse_builder) Build() *SetReconcilerErrorForTeamResponse {
	m0 := &SetReconcilerErrorForTeamResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type RemoveReconcilerErrorForTeamRequest struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TeamSlug       string                 `protobuf:"bytes,1,opt,name=team_slug,json=teamSlug,proto3"`
	xxx_hidden_ReconcilerName string                 `protobuf:"bytes,2,opt,name=reconciler_name,json=reconcilerName,proto3"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *RemoveReconcilerErrorForTeamRequest) Reset() {
	*x = RemoveReconcilerErrorForTeamRequest{}
	mi := &file_reconcilers_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveReconcilerErrorForTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveReconcilerErrorForTeamRequest) ProtoMessage() {}

func (x *RemoveReconcilerErrorForTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reconcilers_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RemoveReconcilerErrorForTeamRequest) GetTeamSlug() string {
	if x != nil {
		return x.xxx_hidden_TeamSlug
	}
	return ""
}

func (x *RemoveReconcilerErrorForTeamRequest) GetReconcilerName() string {
	if x != nil {
		return x.xxx_hidden_ReconcilerName
	}
	return ""
}

func (x *RemoveReconcilerErrorForTeamRequest) SetTeamSlug(v string) {
	x.xxx_hidden_TeamSlug = v
}

func (x *RemoveReconcilerErrorForTeamRequest) SetReconcilerName(v string) {
	x.xxx_hidden_ReconcilerName = v
}

type RemoveReconcilerErrorForTeamRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TeamSlug       string
	ReconcilerName string
}

func (b0 RemoveReconcilerErrorForTeamRequest_builder) Build() *RemoveReconcilerErrorForTeamRequest {
	m0 := &RemoveReconcilerErrorForTeamRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TeamSlug = b.TeamSlug
	x.xxx_hidden_ReconcilerName = b.ReconcilerName
	return m0
}

type RemoveReconcilerErrorForTeamResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveReconcilerErrorForTeamResponse) Reset() {
	*x = RemoveReconcilerErrorForTeamResponse{}
	mi := &file_reconcilers_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveReconcilerErrorForTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveReconcilerErrorForTeamResponse) ProtoMessage() {}

func (x *RemoveReconcilerErrorForTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reconcilers_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type RemoveReconcilerErrorForTeamResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 RemoveReconcilerErrorForTeamResponse_builder) Build() *RemoveReconcilerErrorForTeamResponse {
	m0 := &RemoveReconcilerErrorForTeamResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type Reconciler struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_DisplayName string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3"`
	xxx_hidden_Description string                 `protobuf:"bytes,3,opt,name=description,proto3"`
	xxx_hidden_Enabled     bool                   `protobuf:"varint,4,opt,name=enabled,proto3"`
	xxx_hidden_MemberAware bool                   `protobuf:"varint,5,opt,name=member_aware,json=memberAware,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Reconciler) Reset() {
	*x = Reconciler{}
	mi := &file_reconcilers_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reconciler) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reconciler) ProtoMessage() {}

func (x *Reconciler) ProtoReflect() protoreflect.Message {
	mi := &file_reconcilers_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Reconciler) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *Reconciler) GetDisplayName() string {
	if x != nil {
		return x.xxx_hidden_DisplayName
	}
	return ""
}

func (x *Reconciler) GetDescription() string {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return ""
}

func (x *Reconciler) GetEnabled() bool {
	if x != nil {
		return x.xxx_hidden_Enabled
	}
	return false
}

func (x *Reconciler) GetMemberAware() bool {
	if x != nil {
		return x.xxx_hidden_MemberAware
	}
	return false
}

func (x *Reconciler) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *Reconciler) SetDisplayName(v string) {
	x.xxx_hidden_DisplayName = v
}

func (x *Reconciler) SetDescription(v string) {
	x.xxx_hidden_Description = v
}

func (x *Reconciler) SetEnabled(v bool) {
	x.xxx_hidden_Enabled = v
}

func (x *Reconciler) SetMemberAware(v bool) {
	x.xxx_hidden_MemberAware = v
}

type Reconciler_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name        string
	DisplayName string
	Description string
	Enabled     bool
	MemberAware bool
}

func (b0 Reconciler_builder) Build() *Reconciler {
	m0 := &Reconciler{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_DisplayName = b.DisplayName
	x.xxx_hidden_Description = b.Description
	x.xxx_hidden_Enabled = b.Enabled
	x.xxx_hidden_MemberAware = b.MemberAware
	return m0
}

type ReconcilerConfig struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key         string                 `protobuf:"bytes,1,opt,name=key,proto3"`
	xxx_hidden_DisplayName string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3"`
	xxx_hidden_Description string                 `protobuf:"bytes,3,opt,name=description,proto3"`
	xxx_hidden_Value       string                 `protobuf:"bytes,4,opt,name=value,proto3"`
	xxx_hidden_Secret      bool                   `protobuf:"varint,5,opt,name=secret,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ReconcilerConfig) Reset() {
	*x = ReconcilerConfig{}
	mi := &file_reconcilers_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcilerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcilerConfig) ProtoMessage() {}

func (x *ReconcilerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_reconcilers_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ReconcilerConfig) GetKey() string {
	if x != nil {
		return x.xxx_hidden_Key
	}
	return ""
}

func (x *ReconcilerConfig) GetDisplayName() string {
	if x != nil {
		return x.xxx_hidden_DisplayName
	}
	return ""
}

func (x *ReconcilerConfig) GetDescription() string {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return ""
}

func (x *ReconcilerConfig) GetValue() string {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return ""
}

func (x *ReconcilerConfig) GetSecret() bool {
	if x != nil {
		return x.xxx_hidden_Secret
	}
	return false
}

func (x *ReconcilerConfig) SetKey(v string) {
	x.xxx_hidden_Key = v
}

func (x *ReconcilerConfig) SetDisplayName(v string) {
	x.xxx_hidden_DisplayName = v
}

func (x *ReconcilerConfig) SetDescription(v string) {
	x.xxx_hidden_Description = v
}

func (x *ReconcilerConfig) SetValue(v string) {
	x.xxx_hidden_Value = v
}

func (x *ReconcilerConfig) SetSecret(v bool) {
	x.xxx_hidden_Secret = v
}

type ReconcilerConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Key         string
	DisplayName string
	Description string
	Value       string
	Secret      bool
}

func (b0 ReconcilerConfig_builder) Build() *ReconcilerConfig {
	m0 := &ReconcilerConfig{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Key = b.Key
	x.xxx_hidden_DisplayName = b.DisplayName
	x.xxx_hidden_Description = b.Description
	x.xxx_hidden_Value = b.Value
	x.xxx_hidden_Secret = b.Secret
	return m0
}

type ReconcilerConfigSpec struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key         string                 `protobuf:"bytes,1,opt,name=key,proto3"`
	xxx_hidden_DisplayName string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3"`
	xxx_hidden_Description string                 `protobuf:"bytes,3,opt,name=description,proto3"`
	xxx_hidden_Secret      bool                   `protobuf:"varint,4,opt,name=secret,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ReconcilerConfigSpec) Reset() {
	*x = ReconcilerConfigSpec{}
	mi := &file_reconcilers_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcilerConfigSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcilerConfigSpec) ProtoMessage() {}

func (x *ReconcilerConfigSpec) ProtoReflect() protoreflect.Message {
	mi := &file_reconcilers_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ReconcilerConfigSpec) GetKey() string {
	if x != nil {
		return x.xxx_hidden_Key
	}
	return ""
}

func (x *ReconcilerConfigSpec) GetDisplayName() string {
	if x != nil {
		return x.xxx_hidden_DisplayName
	}
	return ""
}

func (x *ReconcilerConfigSpec) GetDescription() string {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return ""
}

func (x *ReconcilerConfigSpec) GetSecret() bool {
	if x != nil {
		return x.xxx_hidden_Secret
	}
	return false
}

func (x *ReconcilerConfigSpec) SetKey(v string) {
	x.xxx_hidden_Key = v
}

func (x *ReconcilerConfigSpec) SetDisplayName(v string) {
	x.xxx_hidden_DisplayName = v
}

func (x *ReconcilerConfigSpec) SetDescription(v string) {
	x.xxx_hidden_Description = v
}

func (x *ReconcilerConfigSpec) SetSecret(v bool) {
	x.xxx_hidden_Secret = v
}

type ReconcilerConfigSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Key         string
	DisplayName string
	Description string
	Secret      bool
}

func (b0 ReconcilerConfigSpec_builder) Build() *ReconcilerConfigSpec {
	m0 := &ReconcilerConfigSpec{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Key = b.Key
	x.xxx_hidden_DisplayName = b.DisplayName
	x.xxx_hidden_Description = b.Description
	x.xxx_hidden_Secret = b.Secret
	return m0
}

type NewReconciler struct {
	state                      protoimpl.MessageState   `protogen:"opaque.v1"`
	xxx_hidden_Name            string                   `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_DisplayName     string                   `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3"`
	xxx_hidden_Description     string                   `protobuf:"bytes,3,opt,name=description,proto3"`
	xxx_hidden_MemberAware     bool                     `protobuf:"varint,4,opt,name=member_aware,json=memberAware,proto3"`
	xxx_hidden_Config          *[]*ReconcilerConfigSpec `protobuf:"bytes,5,rep,name=config,proto3"`
	xxx_hidden_EnableByDefault bool                     `protobuf:"varint,6,opt,name=enableByDefault,proto3"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *NewReconciler) Reset() {
	*x = NewReconciler{}
	mi := &file_reconcilers_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewReconciler) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewReconciler) ProtoMessage() {}

func (x *NewReconciler) ProtoReflect() protoreflect.Message {
	mi := &file_reconcilers_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NewReconciler) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *NewReconciler) GetDisplayName() string {
	if x != nil {
		return x.xxx_hidden_DisplayName
	}
	return ""
}

func (x *NewReconciler) GetDescription() string {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return ""
}

func (x *NewReconciler) GetMemberAware() bool {
	if x != nil {
		return x.xxx_hidden_MemberAware
	}
	return false
}

func (x *NewReconciler) GetConfig() []*ReconcilerConfigSpec {
	if x != nil {
		if x.xxx_hidden_Config != nil {
			return *x.xxx_hidden_Config
		}
	}
	return nil
}

func (x *NewReconciler) GetEnableByDefault() bool {
	if x != nil {
		return x.xxx_hidden_EnableByDefault
	}
	return false
}

func (x *NewReconciler) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *NewReconciler) SetDisplayName(v string) {
	x.xxx_hidden_DisplayName = v
}

func (x *NewReconciler) SetDescription(v string) {
	x.xxx_hidden_Description = v
}

func (x *NewReconciler) SetMemberAware(v bool) {
	x.xxx_hidden_MemberAware = v
}

func (x *NewReconciler) SetConfig(v []*ReconcilerConfigSpec) {
	x.xxx_hidden_Config = &v
}

func (x *NewReconciler) SetEnableByDefault(v bool) {
	x.xxx_hidden_EnableByDefault = v
}

type NewReconciler_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name            string
	DisplayName     string
	Description     string
	MemberAware     bool
	Config          []*ReconcilerConfigSpec
	EnableByDefault bool
}

func (b0 NewReconciler_builder) Build() *NewReconciler {
	m0 := &NewReconciler{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_DisplayName = b.DisplayName
	x.xxx_hidden_Description = b.Description
	x.xxx_hidden_MemberAware = b.MemberAware
	x.xxx_hidden_Config = &b.Config
	x.xxx_hidden_EnableByDefault = b.EnableByDefault
	return m0
}

type RegisterReconcilerRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Reconcilers *[]*NewReconciler      `protobuf:"bytes,1,rep,name=reconcilers,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RegisterReconcilerRequest) Reset() {
	*x = RegisterReconcilerRequest{}
	mi := &file_reconcilers_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReconcilerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReconcilerRequest) ProtoMessage() {}

func (x *RegisterReconcilerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reconcilers_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RegisterReconcilerRequest) GetReconcilers() []*NewReconciler {
	if x != nil {
		if x.xxx_hidden_Reconcilers != nil {
			return *x.xxx_hidden_Reconcilers
		}
	}
	return nil
}

func (x *RegisterReconcilerRequest) SetReconcilers(v []*NewReconciler) {
	x.xxx_hidden_Reconcilers = &v
}

type RegisterReconcilerRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Reconcilers []*NewReconciler
}

func (b0 RegisterReconcilerRequest_builder) Build() *RegisterReconcilerRequest {
	m0 := &RegisterReconcilerRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Reconcilers = &b.Reconcilers
	return m0
}

type RegisterReconcilerResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReconcilerResponse) Reset() {
	*x = RegisterReconcilerResponse{}
	mi := &file_reconcilers_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReconcilerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReconcilerResponse) ProtoMessage() {}

func (x *RegisterReconcilerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reconcilers_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type RegisterReconcilerResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 RegisterReconcilerResponse_builder) Build() *RegisterReconcilerResponse {
	m0 := &RegisterReconcilerResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type GetReconcilerRequest struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetReconcilerRequest) Reset() {
	*x = GetReconcilerRequest{}
	mi := &file_reconcilers_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReconcilerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReconcilerRequest) ProtoMessage() {}

func (x *GetReconcilerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reconcilers_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetReconcilerRequest) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *GetReconcilerRequest) SetName(v string) {
	x.xxx_hidden_Name = v
}

type GetReconcilerRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name string
}

func (b0 GetReconcilerRequest_builder) Build() *GetReconcilerRequest {
	m0 := &GetReconcilerRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	return m0
}

type GetReconcilerResponse struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Reconciler *Reconciler            `protobuf:"bytes,1,opt,name=reconciler,proto3"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetReconcilerResponse) Reset() {
	*x = GetReconcilerResponse{}
	mi := &file_reconcilers_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReconcilerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReconcilerResponse) ProtoMessage() {}

func (x *GetReconcilerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reconcilers_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetReconcilerResponse) GetReconciler() *Reconciler {
	if x != nil {
		return x.xxx_hidden_Reconciler
	}
	return nil
}

func (x *GetReconcilerResponse) SetReconciler(v *Reconciler) {
	x.xxx_hidden_Reconciler = v
}

func (x *GetReconcilerResponse) HasReconciler() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Reconciler != nil
}

func (x *GetReconcilerResponse) ClearReconciler() {
	x.xxx_hidden_Reconciler = nil
}

type GetReconcilerResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Reconciler *Reconciler
}

func (b0 GetReconcilerResponse_builder) Build() *GetReconcilerResponse {
	m0 := &GetReconcilerResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Reconciler = b.Reconciler
	return m0
}

type ListReconcilersRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Limit  int64                  `protobuf:"varint,1,opt,name=limit,proto3"`
	xxx_hidden_Offset int64                  `protobuf:"varint,2,opt,name=offset,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListReconcilersRequest) Reset() {
	*x = ListReconcilersRequest{}
	mi := &file_reconcilers_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReconcilersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReconcilersRequest) ProtoMessage() {}

func (x *ListReconcilersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reconcilers_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListReconcilersRequest) GetLimit() int64 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *ListReconcilersRequest) GetOffset() int64 {
	if x != nil {
		return x.xxx_hidden_Offset
	}
	return 0
}

func (x *ListReconcilersRequest) SetLimit(v int64) {
	x.xxx_hidden_Limit = v
}

func (x *ListReconcilersRequest) SetOffset(v int64) {
	x.xxx_hidden_Offset = v
}

type ListReconcilersRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Limit  int64
	Offset int64
}

func (b0 ListReconcilersRequest_builder) Build() *ListReconcilersRequest {
	m0 := &ListReconcilersRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Limit = b.Limit
	x.xxx_hidden_Offset = b.Offset
	return m0
}

type ListReconcilersResponse struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Nodes    *[]*Reconciler         `protobuf:"bytes,1,rep,name=nodes,proto3"`
	xxx_hidden_PageInfo *PageInfo              `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListReconcilersResponse) Reset() {
	*x = ListReconcilersResponse{}
	mi := &file_reconcilers_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReconcilersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReconcilersResponse) ProtoMessage() {}

func (x *ListReconcilersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reconcilers_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListReconcilersResponse) GetNodes() []*Reconciler {
	if x != nil {
		if x.xxx_hidden_Nodes != nil {
			return *x.xxx_hidden_Nodes
		}
	}
	return nil
}

func (x *ListReconcilersResponse) GetPageInfo() *PageInfo {
	if x != nil {
		return x.xxx_hidden_PageInfo
	}
	return nil
}

func (x *ListReconcilersResponse) SetNodes(v []*Reconciler) {
	x.xxx_hidden_Nodes = &v
}

func (x *ListReconcilersResponse) SetPageInfo(v *PageInfo) {
	x.xxx_hidden_PageInfo = v
}

func (x *ListReconcilersResponse) HasPageInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_PageInfo != nil
}

func (x *ListReconcilersResponse) ClearPageInfo() {
	x.xxx_hidden_PageInfo = nil
}

type ListReconcilersResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Nodes    []*Reconciler
	PageInfo *PageInfo
}

func (b0 ListReconcilersResponse_builder) Build() *ListReconcilersResponse {
	m0 := &ListReconcilersResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Nodes = &b.Nodes
	x.xxx_hidden_PageInfo = b.PageInfo
	return m0
}

type ConfigReconcilerRequest struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Limit          int64                  `protobuf:"varint,1,opt,name=limit,proto3"`
	xxx_hidden_Offset         int64                  `protobuf:"varint,2,opt,name=offset,proto3"`
	xxx_hidden_ReconcilerName string                 `protobuf:"bytes,3,opt,name=reconciler_name,json=reconcilerName,proto3"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ConfigReconcilerRequest) Reset() {
	*x = ConfigReconcilerRequest{}
	mi := &file_reconcilers_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigReconcilerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigReconcilerRequest) ProtoMessage() {}

func (x *ConfigReconcilerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reconcilers_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConfigReconcilerRequest) GetLimit() int64 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *ConfigReconcilerRequest) GetOffset() int64 {
	if x != nil {
		return x.xxx_hidden_Offset
	}
	return 0
}

func (x *ConfigReconcilerRequest) GetReconcilerName() string {
	if x != nil {
		return x.xxx_hidden_ReconcilerName
	}
	return ""
}

func (x *ConfigReconcilerRequest) SetLimit(v int64) {
	x.xxx_hidden_Limit = v
}

func (x *ConfigReconcilerRequest) SetOffset(v int64) {
	x.xxx_hidden_Offset = v
}

func (x *ConfigReconcilerRequest) SetReconcilerName(v string) {
	x.xxx_hidden_ReconcilerName = v
}

type ConfigReconcilerRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Limit          int64
	Offset         int64
	ReconcilerName string
}

func (b0 ConfigReconcilerRequest_builder) Build() *ConfigReconcilerRequest {
	m0 := &ConfigReconcilerRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Limit = b.Limit
	x.xxx_hidden_Offset = b.Offset
	x.xxx_hidden_ReconcilerName = b.ReconcilerName
	return m0
}

type ConfigReconcilerResponse struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Nodes    *[]*ReconcilerConfig   `protobuf:"bytes,1,rep,name=nodes,proto3"`
	xxx_hidden_PageInfo *PageInfo              `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ConfigReconcilerResponse) Reset() {
	*x = ConfigReconcilerResponse{}
	mi := &file_reconcilers_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigReconcilerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigReconcilerResponse) ProtoMessage() {}

func (x *ConfigReconcilerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reconcilers_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConfigReconcilerResponse) GetNodes() []*ReconcilerConfig {
	if x != nil {
		if x.xxx_hidden_Nodes != nil {
			return *x.xxx_hidden_Nodes
		}
	}
	return nil
}

func (x *ConfigReconcilerResponse) GetPageInfo() *PageInfo {
	if x != nil {
		return x.xxx_hidden_PageInfo
	}
	return nil
}

func (x *ConfigReconcilerResponse) SetNodes(v []*ReconcilerConfig) {
	x.xxx_hidden_Nodes = &v
}

func (x *ConfigReconcilerResponse) SetPageInfo(v *PageInfo) {
	x.xxx_hidden_PageInfo = v
}

func (x *ConfigReconcilerResponse) HasPageInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_PageInfo != nil
}

func (x *ConfigReconcilerResponse) ClearPageInfo() {
	x.xxx_hidden_PageInfo = nil
}

type ConfigReconcilerResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Nodes    []*ReconcilerConfig
	PageInfo *PageInfo
}

func (b0 ConfigReconcilerResponse_builder) Build() *ConfigReconcilerResponse {
	m0 := &ConfigReconcilerResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Nodes = &b.Nodes
	x.xxx_hidden_PageInfo = b.PageInfo
	return m0
}

type ReconcilerState struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id             string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	xxx_hidden_ReconcilerName string                 `protobuf:"bytes,2,opt,name=reconciler_name,json=reconcilerName,proto3"`
	xxx_hidden_TeamSlug       string                 `protobuf:"bytes,3,opt,name=team_slug,json=teamSlug,proto3"`
	xxx_hidden_Value          []byte                 `protobuf:"bytes,4,opt,name=value,proto3"`
	xxx_hidden_CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3"`
	xxx_hidden_UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ReconcilerState) Reset() {
	*x = ReconcilerState{}
	mi := &file_reconcilers_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcilerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcilerState) ProtoMessage() {}

func (x *ReconcilerState) ProtoReflect() protoreflect.Message {
	mi := &file_reconcilers_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ReconcilerState) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *ReconcilerState) GetReconcilerName() string {
	if x != nil {
		return x.xxx_hidden_ReconcilerName
	}
	return ""
}

func (x *ReconcilerState) GetTeamSlug() string {
	if x != nil {
		return x.xxx_hidden_TeamSlug
	}
	return ""
}

func (x *ReconcilerState) GetValue() []byte {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return nil
}

func (x *ReconcilerState) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *ReconcilerState) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_UpdatedAt
	}
	return nil
}

func (x *ReconcilerState) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *ReconcilerState) SetReconcilerName(v string) {
	x.xxx_hidden_ReconcilerName = v
}

func (x *ReconcilerState) SetTeamSlug(v string) {
	x.xxx_hidden_TeamSlug = v
}

func (x *ReconcilerState) SetValue(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Value = v
}

func (x *ReconcilerState) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *ReconcilerState) SetUpdatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_UpdatedAt = v
}

func (x *ReconcilerState) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *ReconcilerState) HasUpdatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdatedAt != nil
}

func (x *ReconcilerState) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *ReconcilerState) ClearUpdatedAt() {
	x.xxx_hidden_UpdatedAt = nil
}

type ReconcilerState_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id             string
	ReconcilerName string
	TeamSlug       string
	Value          []byte
	CreatedAt      *timestamppb.Timestamp
	UpdatedAt      *timestamppb.Timestamp
}

func (b0 ReconcilerState_builder) Build() *ReconcilerState {
	m0 := &ReconcilerState{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_ReconcilerName = b.ReconcilerName
	x.xxx_hidden_TeamSlug = b.TeamSlug
	x.xxx_hidden_Value = b.Value
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_UpdatedAt = b.UpdatedAt
	return m0
}

type SaveReconcilerStateResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveReconcilerStateResponse) Reset() {
	*x = SaveReconcilerStateResponse{}
	mi := &file_reconcilers_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveReconcilerStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveReconcilerStateResponse) ProtoMessage() {}

func (x *SaveReconcilerStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reconcilers_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type SaveReconcilerStateResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 SaveReconcilerStateResponse_builder) Build() *SaveReconcilerStateResponse {
	m0 := &SaveReconcilerStateResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type SaveReconcilerStateRequest struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ReconcilerName string                 `protobuf:"bytes,1,opt,name=reconciler_name,json=reconcilerName,proto3"`
	xxx_hidden_TeamSlug       string                 `protobuf:"bytes,2,opt,name=team_slug,json=teamSlug,proto3"`
	xxx_hidden_Value          []byte                 `protobuf:"bytes,3,opt,name=value,proto3"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *SaveReconcilerStateRequest) Reset() {
	*x = SaveReconcilerStateRequest{}
	mi := &file_reconcilers_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveReconcilerStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveReconcilerStateRequest) ProtoMessage() {}

func (x *SaveReconcilerStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reconcilers_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SaveReconcilerStateRequest) GetReconcilerName() string {
	if x != nil {
		return x.xxx_hidden_ReconcilerName
	}
	return ""
}

func (x *SaveReconcilerStateRequest) GetTeamSlug() string {
	if x != nil {
		return x.xxx_hidden_TeamSlug
	}
	return ""
}

func (x *SaveReconcilerStateRequest) GetValue() []byte {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return nil
}

func (x *SaveReconcilerStateRequest) SetReconcilerName(v string) {
	x.xxx_hidden_ReconcilerName = v
}

func (x *SaveReconcilerStateRequest) SetTeamSlug(v string) {
	x.xxx_hidden_TeamSlug = v
}

func (x *SaveReconcilerStateRequest) SetValue(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Value = v
}

type SaveReconcilerStateRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ReconcilerName string
	TeamSlug       string
	Value          []byte
}

func (b0 SaveReconcilerStateRequest_builder) Build() *SaveReconcilerStateRequest {
	m0 := &SaveReconcilerStateRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ReconcilerName = b.ReconcilerName
	x.xxx_hidden_TeamSlug = b.TeamSlug
	x.xxx_hidden_Value = b.Value
	return m0
}

type DeleteReconcilerStateRequest struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ReconcilerName string                 `protobuf:"bytes,1,opt,name=reconciler_name,json=reconcilerName,proto3"`
	xxx_hidden_TeamSlug       string                 `protobuf:"bytes,2,opt,name=team_slug,json=teamSlug,proto3"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *DeleteReconcilerStateRequest) Reset() {
	*x = DeleteReconcilerStateRequest{}
	mi := &file_reconcilers_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReconcilerStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReconcilerStateRequest) ProtoMessage() {}

func (x *DeleteReconcilerStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reconcilers_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteReconcilerStateRequest) GetReconcilerName() string {
	if x != nil {
		return x.xxx_hidden_ReconcilerName
	}
	return ""
}

func (x *DeleteReconcilerStateRequest) GetTeamSlug() string {
	if x != nil {
		return x.xxx_hidden_TeamSlug
	}
	return ""
}

func (x *DeleteReconcilerStateRequest) SetReconcilerName(v string) {
	x.xxx_hidden_ReconcilerName = v
}

func (x *DeleteReconcilerStateRequest) SetTeamSlug(v string) {
	x.xxx_hidden_TeamSlug = v
}

type DeleteReconcilerStateRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ReconcilerName string
	TeamSlug       string
}

func (b0 DeleteReconcilerStateRequest_builder) Build() *DeleteReconcilerStateRequest {
	m0 := &DeleteReconcilerStateRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ReconcilerName = b.ReconcilerName
	x.xxx_hidden_TeamSlug = b.TeamSlug
	return m0
}

type DeleteReconcilerStateResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReconcilerStateResponse) Reset() {
	*x = DeleteReconcilerStateResponse{}
	mi := &file_reconcilers_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReconcilerStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReconcilerStateResponse) ProtoMessage() {}

func (x *DeleteReconcilerStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reconcilers_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type DeleteReconcilerStateResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 DeleteReconcilerStateResponse_builder) Build() *DeleteReconcilerStateResponse {
	m0 := &DeleteReconcilerStateResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type GetReconcilerStateRequest struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ReconcilerName string                 `protobuf:"bytes,3,opt,name=reconciler_name,json=reconcilerName,proto3"`
	xxx_hidden_TeamSlug       string                 `protobuf:"bytes,4,opt,name=team_slug,json=teamSlug,proto3"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *GetReconcilerStateRequest) Reset() {
	*x = GetReconcilerStateRequest{}
	mi := &file_reconcilers_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReconcilerStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReconcilerStateRequest) ProtoMessage() {}

func (x *GetReconcilerStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reconcilers_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetReconcilerStateRequest) GetReconcilerName() string {
	if x != nil {
		return x.xxx_hidden_ReconcilerName
	}
	return ""
}

func (x *GetReconcilerStateRequest) GetTeamSlug() string {
	if x != nil {
		return x.xxx_hidden_TeamSlug
	}
	return ""
}

func (x *GetReconcilerStateRequest) SetReconcilerName(v string) {
	x.xxx_hidden_ReconcilerName = v
}

func (x *GetReconcilerStateRequest) SetTeamSlug(v string) {
	x.xxx_hidden_TeamSlug = v
}

type GetReconcilerStateRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ReconcilerName string
	TeamSlug       string
}

func (b0 GetReconcilerStateRequest_builder) Build() *GetReconcilerStateRequest {
	m0 := &GetReconcilerStateRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ReconcilerName = b.ReconcilerName
	x.xxx_hidden_TeamSlug = b.TeamSlug
	return m0
}

type GetReconcilerStateResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_State *ReconcilerState       `protobuf:"bytes,1,opt,name=state,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetReconcilerStateResponse) Reset() {
	*x = GetReconcilerStateResponse{}
	mi := &file_reconcilers_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReconcilerStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReconcilerStateResponse) ProtoMessage() {}

func (x *GetReconcilerStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reconcilers_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetReconcilerStateResponse) GetState() *ReconcilerState {
	if x != nil {
		return x.xxx_hidden_State
	}
	return nil
}

func (x *GetReconcilerStateResponse) SetState(v *ReconcilerState) {
	x.xxx_hidden_State = v
}

func (x *GetReconcilerStateResponse) HasState() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_State != nil
}

func (x *GetReconcilerStateResponse) ClearState() {
	x.xxx_hidden_State = nil
}

type GetReconcilerStateResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	State *ReconcilerState
}

func (b0 GetReconcilerStateResponse_builder) Build() *GetReconcilerStateResponse {
	m0 := &GetReconcilerStateResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_State = b.State
	return m0
}

var File_reconcilers_proto protoreflect.FileDescriptor

const file_reconcilers_proto_rawDesc = "" +
	"\n" +
	"\x11reconcilers.proto\x12\x11nais.api.protobuf\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x10pagination.proto\"8\n" +
	"\x19SuccessfulTeamSyncRequest\x12\x1b\n" +
	"\tteam_slug\x18\x01 \x01(\tR\bteamSlug\"\x1c\n" +
	"\x1aSuccessfulTeamSyncResponse\"\xb4\x01\n" +
	" SetReconcilerErrorForTeamRequest\x12\x1b\n" +
	"\tteam_slug\x18\x01 \x01(\tR\bteamSlug\x12'\n" +
	"\x0freconciler_name\x18\x02 \x01(\tR\x0ereconcilerName\x12%\n" +
	"\x0ecorrelation_id\x18\x03 \x01(\tR\rcorrelationId\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"#\n" +
	"!SetReconcilerErrorForTeamResponse\"k\n" +
	"#RemoveReconcilerErrorForTeamRequest\x12\x1b\n" +
	"\tteam_slug\x18\x01 \x01(\tR\bteamSlug\x12'\n" +
	"\x0freconciler_name\x18\x02 \x01(\tR\x0ereconcilerName\"&\n" +
	"$RemoveReconcilerErrorForTeamResponse\"\xa2\x01\n" +
	"\n" +
	"Reconciler\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12!\n" +
	"\fmember_aware\x18\x05 \x01(\bR\vmemberAware\"\x97\x01\n" +
	"\x10ReconcilerConfig\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x16\n" +
	"\x06secret\x18\x05 \x01(\bR\x06secret\"\x85\x01\n" +
	"\x14ReconcilerConfigSpec\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06secret\x18\x04 \x01(\bR\x06secret\"\xf6\x01\n" +
	"\rNewReconciler\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12!\n" +
	"\fmember_aware\x18\x04 \x01(\bR\vmemberAware\x12?\n" +
	"\x06config\x18\x05 \x03(\v2'.nais.api.protobuf.ReconcilerConfigSpecR\x06config\x12(\n" +
	"\x0fenableByDefault\x18\x06 \x01(\bR\x0fenableByDefault\"_\n" +
	"\x19RegisterReconcilerRequest\x12B\n" +
	"\vreconcilers\x18\x01 \x03(\v2 .nais.api.protobuf.NewReconcilerR\vreconcilers\"\x1c\n" +
	"\x1aRegisterReconcilerResponse\"*\n" +
	"\x14GetReconcilerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"V\n" +
	"\x15GetReconcilerResponse\x12=\n" +
	"\n" +
	"reconciler\x18\x01 \x01(\v2\x1d.nais.api.protobuf.ReconcilerR\n" +
	"reconciler\"F\n" +
	"\x16ListReconcilersRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\"\x88\x01\n" +
	"\x17ListReconcilersResponse\x123\n" +
	"\x05nodes\x18\x01 \x03(\v2\x1d.nais.api.protobuf.ReconcilerR\x05nodes\x128\n" +
	"\tpage_info\x18\x02 \x01(\v2\x1b.nais.api.protobuf.PageInfoR\bpageInfo\"p\n" +
	"\x17ConfigReconcilerRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12'\n" +
	"\x0freconciler_name\x18\x03 \x01(\tR\x0ereconcilerName\"\x8f\x01\n" +
	"\x18ConfigReconcilerResponse\x129\n" +
	"\x05nodes\x18\x01 \x03(\v2#.nais.api.protobuf.ReconcilerConfigR\x05nodes\x128\n" +
	"\tpage_info\x18\x02 \x01(\v2\x1b.nais.api.protobuf.PageInfoR\bpageInfo\"\xf3\x01\n" +
	"\x0fReconcilerState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0freconciler_name\x18\x02 \x01(\tR\x0ereconcilerName\x12\x1b\n" +
	"\tteam_slug\x18\x03 \x01(\tR\bteamSlug\x12\x14\n" +
	"\x05value\x18\x04 \x01(\fR\x05value\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x1d\n" +
	"\x1bSaveReconcilerStateResponse\"x\n" +
	"\x1aSaveReconcilerStateRequest\x12'\n" +
	"\x0freconciler_name\x18\x01 \x01(\tR\x0ereconcilerName\x12\x1b\n" +
	"\tteam_slug\x18\x02 \x01(\tR\bteamSlug\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"d\n" +
	"\x1cDeleteReconcilerStateRequest\x12'\n" +
	"\x0freconciler_name\x18\x01 \x01(\tR\x0ereconcilerName\x12\x1b\n" +
	"\tteam_slug\x18\x02 \x01(\tR\bteamSlug\"\x1f\n" +
	"\x1dDeleteReconcilerStateResponse\"a\n" +
	"\x19GetReconcilerStateRequest\x12'\n" +
	"\x0freconciler_name\x18\x03 \x01(\tR\x0ereconcilerName\x12\x1b\n" +
	"\tteam_slug\x18\x04 \x01(\tR\bteamSlug\"V\n" +
	"\x1aGetReconcilerStateResponse\x128\n" +
	"\x05state\x18\x01 \x01(\v2\".nais.api.protobuf.ReconcilerStateR\x05state2\xf8\b\n" +
	"\vReconcilers\x12i\n" +
	"\bRegister\x12,.nais.api.protobuf.RegisterReconcilerRequest\x1a-.nais.api.protobuf.RegisterReconcilerResponse\"\x00\x12Z\n" +
	"\x03Get\x12'.nais.api.protobuf.GetReconcilerRequest\x1a(.nais.api.protobuf.GetReconcilerResponse\"\x00\x12_\n" +
	"\x04List\x12).nais.api.protobuf.ListReconcilersRequest\x1a*.nais.api.protobuf.ListReconcilersResponse\"\x00\x12c\n" +
	"\x06Config\x12*.nais.api.protobuf.ConfigReconcilerRequest\x1a+.nais.api.protobuf.ConfigReconcilerResponse\"\x00\x12\x88\x01\n" +
	"\x19SetReconcilerErrorForTeam\x123.nais.api.protobuf.SetReconcilerErrorForTeamRequest\x1a4.nais.api.protobuf.SetReconcilerErrorForTeamResponse\"\x00\x12\x91\x01\n" +
	"\x1cRemoveReconcilerErrorForTeam\x126.nais.api.protobuf.RemoveReconcilerErrorForTeamRequest\x1a7.nais.api.protobuf.RemoveReconcilerErrorForTeamResponse\"\x00\x12s\n" +
	"\x12SuccessfulTeamSync\x12,.nais.api.protobuf.SuccessfulTeamSyncRequest\x1a-.nais.api.protobuf.SuccessfulTeamSyncResponse\"\x00\x12l\n" +
	"\tSaveState\x12-.nais.api.protobuf.SaveReconcilerStateRequest\x1a..nais.api.protobuf.SaveReconcilerStateResponse\"\x00\x12f\n" +
	"\x05State\x12,.nais.api.protobuf.GetReconcilerStateRequest\x1a-.nais.api.protobuf.GetReconcilerStateResponse\"\x00\x12r\n" +
	"\vDeleteState\x12/.nais.api.protobuf.DeleteReconcilerStateRequest\x1a0.nais.api.protobuf.DeleteReconcilerStateResponse\"\x00B\x1aZ\x18./pkg/apiclient/protoapib\x06proto3"

var file_reconcilers_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_reconcilers_proto_goTypes = []any{
	(*SuccessfulTeamSyncRequest)(nil),            // 0: nais.api.protobuf.SuccessfulTeamSyncRequest
	(*SuccessfulTeamSyncResponse)(nil),           // 1: nais.api.protobuf.SuccessfulTeamSyncResponse
	(*SetReconcilerErrorForTeamRequest)(nil),     // 2: nais.api.protobuf.SetReconcilerErrorForTeamRequest
	(*SetReconcilerErrorForTeamResponse)(nil),    // 3: nais.api.protobuf.SetReconcilerErrorForTeamResponse
	(*RemoveReconcilerErrorForTeamRequest)(nil),  // 4: nais.api.protobuf.RemoveReconcilerErrorForTeamRequest
	(*RemoveReconcilerErrorForTeamResponse)(nil), // 5: nais.api.protobuf.RemoveReconcilerErrorForTeamResponse
	(*Reconciler)(nil),                           // 6: nais.api.protobuf.Reconciler
	(*ReconcilerConfig)(nil),                     // 7: nais.api.protobuf.ReconcilerConfig
	(*ReconcilerConfigSpec)(nil),                 // 8: nais.api.protobuf.ReconcilerConfigSpec
	(*NewReconciler)(nil),                        // 9: nais.api.protobuf.NewReconciler
	(*RegisterReconcilerRequest)(nil),            // 10: nais.api.protobuf.RegisterReconcilerRequest
	(*RegisterReconcilerResponse)(nil),           // 11: nais.api.protobuf.RegisterReconcilerResponse
	(*GetReconcilerRequest)(nil),                 // 12: nais.api.protobuf.GetReconcilerRequest
	(*GetReconcilerResponse)(nil),                // 13: nais.api.protobuf.GetReconcilerResponse
	(*ListReconcilersRequest)(nil),               // 14: nais.api.protobuf.ListReconcilersRequest
	(*ListReconcilersResponse)(nil),              // 15: nais.api.protobuf.ListReconcilersResponse
	(*ConfigReconcilerRequest)(nil),              // 16: nais.api.protobuf.ConfigReconcilerRequest
	(*ConfigReconcilerResponse)(nil),             // 17: nais.api.protobuf.ConfigReconcilerResponse
	(*ReconcilerState)(nil),                      // 18: nais.api.protobuf.ReconcilerState
	(*SaveReconcilerStateResponse)(nil),          // 19: nais.api.protobuf.SaveReconcilerStateResponse
	(*SaveReconcilerStateRequest)(nil),           // 20: nais.api.protobuf.SaveReconcilerStateRequest
	(*DeleteReconcilerStateRequest)(nil),         // 21: nais.api.protobuf.DeleteReconcilerStateRequest
	(*DeleteReconcilerStateResponse)(nil),        // 22: nais.api.protobuf.DeleteReconcilerStateResponse
	(*GetReconcilerStateRequest)(nil),            // 23: nais.api.protobuf.GetReconcilerStateRequest
	(*GetReconcilerStateResponse)(nil),           // 24: nais.api.protobuf.GetReconcilerStateResponse
	(*PageInfo)(nil),                             // 25: nais.api.protobuf.PageInfo
	(*timestamppb.Timestamp)(nil),                // 26: google.protobuf.Timestamp
}
var file_reconcilers_proto_depIdxs = []int32{
	8,  // 0: nais.api.protobuf.NewReconciler.config:type_name -> nais.api.protobuf.ReconcilerConfigSpec
	9,  // 1: nais.api.protobuf.RegisterReconcilerRequest.reconcilers:type_name -> nais.api.protobuf.NewReconciler
	6,  // 2: nais.api.protobuf.GetReconcilerResponse.reconciler:type_name -> nais.api.protobuf.Reconciler
	6,  // 3: nais.api.protobuf.ListReconcilersResponse.nodes:type_name -> nais.api.protobuf.Reconciler
	25, // 4: nais.api.protobuf.ListReconcilersResponse.page_info:type_name -> nais.api.protobuf.PageInfo
	7,  // 5: nais.api.protobuf.ConfigReconcilerResponse.nodes:type_name -> nais.api.protobuf.ReconcilerConfig
	25, // 6: nais.api.protobuf.ConfigReconcilerResponse.page_info:type_name -> nais.api.protobuf.PageInfo
	26, // 7: nais.api.protobuf.ReconcilerState.created_at:type_name -> google.protobuf.Timestamp
	26, // 8: nais.api.protobuf.ReconcilerState.updated_at:type_name -> google.protobuf.Timestamp
	18, // 9: nais.api.protobuf.GetReconcilerStateResponse.state:type_name -> nais.api.protobuf.ReconcilerState
	10, // 10: nais.api.protobuf.Reconcilers.Register:input_type -> nais.api.protobuf.RegisterReconcilerRequest
	12, // 11: nais.api.protobuf.Reconcilers.Get:input_type -> nais.api.protobuf.GetReconcilerRequest
	14, // 12: nais.api.protobuf.Reconcilers.List:input_type -> nais.api.protobuf.ListReconcilersRequest
	16, // 13: nais.api.protobuf.Reconcilers.Config:input_type -> nais.api.protobuf.ConfigReconcilerRequest
	2,  // 14: nais.api.protobuf.Reconcilers.SetReconcilerErrorForTeam:input_type -> nais.api.protobuf.SetReconcilerErrorForTeamRequest
	4,  // 15: nais.api.protobuf.Reconcilers.RemoveReconcilerErrorForTeam:input_type -> nais.api.protobuf.RemoveReconcilerErrorForTeamRequest
	0,  // 16: nais.api.protobuf.Reconcilers.SuccessfulTeamSync:input_type -> nais.api.protobuf.SuccessfulTeamSyncRequest
	20, // 17: nais.api.protobuf.Reconcilers.SaveState:input_type -> nais.api.protobuf.SaveReconcilerStateRequest
	23, // 18: nais.api.protobuf.Reconcilers.State:input_type -> nais.api.protobuf.GetReconcilerStateRequest
	21, // 19: nais.api.protobuf.Reconcilers.DeleteState:input_type -> nais.api.protobuf.DeleteReconcilerStateRequest
	11, // 20: nais.api.protobuf.Reconcilers.Register:output_type -> nais.api.protobuf.RegisterReconcilerResponse
	13, // 21: nais.api.protobuf.Reconcilers.Get:output_type -> nais.api.protobuf.GetReconcilerResponse
	15, // 22: nais.api.protobuf.Reconcilers.List:output_type -> nais.api.protobuf.ListReconcilersResponse
	17, // 23: nais.api.protobuf.Reconcilers.Config:output_type -> nais.api.protobuf.ConfigReconcilerResponse
	3,  // 24: nais.api.protobuf.Reconcilers.SetReconcilerErrorForTeam:output_type -> nais.api.protobuf.SetReconcilerErrorForTeamResponse
	5,  // 25: nais.api.protobuf.Reconcilers.RemoveReconcilerErrorForTeam:output_type -> nais.api.protobuf.RemoveReconcilerErrorForTeamResponse
	1,  // 26: nais.api.protobuf.Reconcilers.SuccessfulTeamSync:output_type -> nais.api.protobuf.SuccessfulTeamSyncResponse
	19, // 27: nais.api.protobuf.Reconcilers.SaveState:output_type -> nais.api.protobuf.SaveReconcilerStateResponse
	24, // 28: nais.api.protobuf.Reconcilers.State:output_type -> nais.api.protobuf.GetReconcilerStateResponse
	22, // 29: nais.api.protobuf.Reconcilers.DeleteState:output_type -> nais.api.protobuf.DeleteReconcilerStateResponse
	20, // [20:30] is the sub-list for method output_type
	10, // [10:20] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_reconcilers_proto_init() }
func file_reconcilers_proto_init() {
	if File_reconcilers_proto != nil {
		return
	}
	file_pagination_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reconcilers_proto_rawDesc), len(file_reconcilers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reconcilers_proto_goTypes,
		DependencyIndexes: file_reconcilers_proto_depIdxs,
		MessageInfos:      file_reconcilers_proto_msgTypes,
	}.Build()
	File_reconcilers_proto = out.File
	file_reconcilers_proto_goTypes = nil
	file_reconcilers_proto_depIdxs = nil
}
