// Code generated by sqlc. DO NOT EDIT.

package auditsql

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/nais/api/internal/slug"
)

type AuditEvent struct {
	ID           uuid.UUID
	CreatedAt    pgtype.Timestamptz
	Actor        string
	Action       string
	ResourceType string
	ResourceName string
	TeamSlug     *slug.Slug
	Data         []byte
	Environment  *string
}
