apiVersion: v1
kind: ConfigMap
metadata:
  name: unmanaged-config-in-staging
data:
  foo: bar
---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    console.nais.io/last-modified-at: "2024-10-18T12:44:57Z"
    console.nais.io/last-modified-by: authenticated@example.com
    reloader.stakater.com/match: "true"
  labels:
    nais.io/managed-by: console
    app.kubernetes.io/managed-by: console
  name: managed-config-in-staging
data:
  api-url: https://example.com
---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    console.nais.io/last-modified-at: "2024-10-18T12:44:57Z"
    console.nais.io/last-modified-by: authenticated@example.com
    reloader.stakater.com/match: "true"
  labels:
    nais.io/managed-by: console
    app.kubernetes.io/managed-by: console
  name: managed-config-in-staging-used-with-filesfrom
data:
  config-file: "{}"
