apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: jobname-1-deprecated-cloudsql
spec:
  image: europe-north1-docker.pkg.dev/nais/navikt/app-name:latest
  schedule: "0 0 * * *"
  gcp:
    sqlInstances:
      - autoBackupHour: 1
        cascadingDelete: true
        collation: nb_NO.UTF8
        databases:
          - envVarPrefix: DB
            name: mydatabase
            users:
              - name: extra_user
        diskAutoresize: true
        diskAutoresizeLimit: 60
        diskSize: 30
        diskType: SSD
        flags:
          - name: max_connections
            value: "50"
        highAvailability: true
        insights:
          enabled: true
          queryStringLength: 4500
          recordApplicationTags: true
          recordClientAddress: true
        maintenance:
          day: 1
          hour: 4
        name: myinstance
        pointInTimeRecovery: true
        retainedBackups: 14
        tier: db-f1-micro
        transactionLogRetentionDays: 3
        type: POSTGRES_13

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: jobname-1-deprecated-cloudsql
  labels:
    app: jobname-1-deprecated-cloudsql
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    metadata:
      labels:
        app: jobname-1-deprecated-cloudsql
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: europe-north1-docker.pkg.dev/nais/navikt/app-name:latest
              command:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: Job
metadata:
  name: jobname-1-deprecated-cloudsql-run1
  labels:
    app: jobname-1-deprecated-cloudsql
spec:
  template:
    spec:
      containers:
        - name: jobname-1-deprecated-cloudsql
          image: europe-north1-docker.pkg.dev/nais/navikt/app-name:latest
status:
  failed: 0
