apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: deprecated-ingress
spec:
  image: europe-north1-docker.pkg.dev/nais/navikt/app-name:latest
  replicas:
    min: 2
    max: 2
  ingresses:
    - "https://error.dev-gcp.nais.io"

---
apiVersion: v1
kind: Pod
metadata:
  name: deprecated-ingress-1
  labels:
    app: deprecated-ingress
  creationTimestamp: "2021-09-30T12:00:00Z"
spec:
  containers:
    - name: deprecated-ingress
      image: europe-north1-docker.pkg.dev/nais/navikt/app-name:latest
status:
  containerStatuses:
    - name: deprecated-ingress
      ready: true
      restartCount: 0
