apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: unsupported-cloud-sql
spec:
  image: europe-north1-docker.pkg.dev/nais/navikt/app-name:latest
  replicas:
    min: 2
    max: 2
  gcp:
    sqlInstances:
    - autoBackupHour: 1
      cascadingDelete: true
      collation: nb_NO.UTF8
      databases:
      - envVarPrefix: DB
        name: mydatabase
        users:
        - name: extra_user
      diskAutoresize: true
      diskAutoresizeLimit: 60
      diskSize: 30
      diskType: SSD
      flags:
      - name: max_connections
        value: "50"
      highAvailability: true
      insights:
        enabled: true
        queryStringLength: 4500
        recordApplicationTags: true
        recordClientAddress: true
      maintenance:
        day: 1
        hour: 4
      name: myinstance
      pointInTimeRecovery: true
      retainedBackups: 14
      tier: db-f1-micro
      transactionLogRetentionDays: 3
      type: POSTGRES_12
---
apiVersion: v1
kind: Pod
metadata:
  name: unsupported-cloud-sql-1
  labels:
    app: unsupported-cloud-sql
  creationTimestamp: "2021-09-30T12:00:00Z"
spec:
  containers:
    - name: unsupported-cloud-sql
      image: europe-north1-docker.pkg.dev/nais/navikt/app-name:latest
status:
  containerStatuses:
    - name: unsupported-cloud-sql
      ready: true
      restartCount: 0
