---
apiVersion: nais.io/v1
kind: Postgres
metadata:
  name: another-db
  namespace: someteamname
spec:
  majorVersion: "16"
status:
  activeBranch: another-db
---
apiVersion: nais.io/v1
kind: PostgresBranch
metadata:
  name: another-db
  namespace: someteamname
spec:
  postgres: another-db
status:
  reconcilePhase: Completed
  conditions:
    - type: cluster.postgresql.cnpg.io/ObservedState
      status: "True"
      reason: Reconciled
      message: "Cluster is in phase: Cluster in healthy state"
      lastTransitionTime: "2026-09-17T00:00:00Z"
