apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: job-running
spec:
  image: europe-north1-docker.pkg.dev/nais/navikt/app-name:latest
  schedule: "0 0 * * *"

---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-running
  labels:
    app: job-running
spec:
  template:
    spec:
      containers:
        - name: job-running
          image: europe-north1-docker.pkg.dev/nais/navikt/app-name:latest
status:
  startTime: "2024-01-24T13:47:00Z"
  ready: 1
