// Code generated by sqlc. DO NOT EDIT.

package restteamsapisql

import (
	"context"

	"github.com/nais/api/internal/slug"
)

type Querier interface {
	ListMembers(ctx context.Context, teamSlug slug.Slug) ([]string, error)
	TeamExists(ctx context.Context, argSlug slug.Slug) (bool, error)
}

var _ Querier = (*Queries)(nil)
