---
apiVersion: nais.io/v1
kind: Postgres
metadata:
  name: audit-enabled
  namespace: audit-postgres-team
spec:
  majorVersion: "16"
status:
  activeBranch: main
---
apiVersion: nais.io/v1
kind: PostgresBranch
metadata:
  name: audit-enabled-main-74f70e60
  namespace: audit-postgres-team
spec:
  postgres: audit-enabled
  branchName: main
status:
  reconcilePhase: Completed
  conditions:
    - type: cluster.postgresql.cnpg.io/ObservedState
      status: "True"
      reason: Reconciled
      message: "Cluster is in phase: Cluster in healthy state"
      lastTransitionTime: "2026-09-17T00:00:00Z"
