#!/usr/bin/env sh
#MISE description="Generate all code"

mise run generate:sql ::: generate:graphql ::: generate:proto
mise run generate:mocks ::: generate:tester_spec
mise run fmt:go ::: fmt:prettier
