#!/usr/bin/env sh
#MISE description="Generate mocks using mockery"

set -e

find internal pkg -type f -name "mock_*.go" -delete
go tool github.com/vektra/mockery/v3 --config ./.configs/mockery.yaml
find internal pkg -type f -name "mock_*.go" -exec go tool mvdan.cc/gofumpt -w {} \;

mise run fmt:go