#!/usr/bin/env sh
#MISE description="Generate mocks using mockery"

set -e

find internal pkg -type f -name "mock_*.go" -delete
mockery --config ./.configs/mockery.yaml
find internal pkg -type f -name "mock_*.go" -exec gofumpt -w {} \;

mise run fmt:go
