#!/usr/bin/env sh
#MISE description="Generate proto code using protoc"

set -e

protoc \
	-I pkg/apiclient/protoapi/schema/ \
	./pkg/apiclient/protoapi/schema/*.proto \
	--go_opt=default_api_level=API_HYBRID \
	--go_out=. \
	--go-grpc_out=.

mise run fmt:go
