apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: failed-netpol-success-app
spec:
  image: europe-north1-docker.pkg.dev/nais/navikt/app-name:latest
  replicas:
    min: 2
    max: 2
  accessPolicy:
    inbound:
      rules:
        - application: failed-netpol
    outbound:
      rules:
        - application: failed-netpol
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: failed-netpol-success-app-1
#   labels:
#     app: failed-netpol-success-app
#   creationTimestamp: "2021-09-30T12:00:00Z"
# spec:
#   containers:
#     - name: failed-netpol-success-app
#       image: europe-north1-docker.pkg.dev/nais/navikt/app-name:latest
# status:
#   containerStatuses:
#     - name: failed-netpol-success-app
#       ready: true
#       restartCount: 0
