apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: no-errors
spec:
  image: europe-north1-docker.pkg.dev/nais/navikt/app-name:latest
  replicas:
    min: 2
    max: 2

---
apiVersion: v1
kind: Pod
metadata:
  name: no-errors-1
  labels:
    app: no-errors
  creationTimestamp: "2021-09-30T12:00:00Z"
spec:
  containers:
    - name: no-errors
      image: europe-north1-docker.pkg.dev/nais/navikt/app-name:latest
status:
  containerStatuses:
    - name: no-errors
      ready: true
      restartCount: 0
