apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: failed-netpol
spec:
  image: europe-north1-docker.pkg.dev/nais/navikt/app-name:latest
  replicas:
    min: 2
    max: 2
  accessPolicy:
    inbound:
      rules:
        - application: other-app
          namespace: other-namespace
        - application: failed-netpol-success-app
    outbound:
      rules:
        - application: failed-netpol-success-app
        - namespace: other-namespace
          application: other-app
---
apiVersion: v1
kind: Pod
metadata:
  name: failed-netpol-1
  labels:
    app: failed-netpol
  creationTimestamp: "2021-09-30T12:00:00Z"
spec:
  containers:
    - name: failed-netpol
      image: europe-north1-docker.pkg.dev/nais/navikt/app-name:latest
status:
  containerStatuses:
    - name: failed-netpol
      ready: true
      restartCount: 0
