apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: failed-netpol
spec:
  image: europe-north1-docker.pkg.dev/nais/navikt/app-name:latest
  schedule: "0 0 * * *"
  accessPolicy:
    inbound:
      rules:
        - application: other-app
          namespace: other-namespace
        - application: failed-netpol-success-app
    outbound:
      rules:
        - application: failed-netpol-success-app
        - namespace: other-namespace
          application: other-app

---
apiVersion: batch/v1
kind: Job
metadata:
  name: failed-netpol
  labels:
    app: failed-netpol
spec:
  template:
    spec:
      containers:
        - name: failed-netpol
          image: europe-north1-docker.pkg.dev/nais/navikt/app-name:latest
status:
  failed: 0
