apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: deprecated-registry
spec:
  image: ghcr.io/navikt/app-name:latest
  schedule: "0 0 * * *"

---
apiVersion: batch/v1
kind: Job
metadata:
  name: deprecated-registry
  labels:
    app: deprecated-registry
spec:
  template:
    spec:
      containers:
        - name: deprecated-registry
          image: ghcr.io/navikt/app-name:latest
status:
  failed: 0
