package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"errors"
	"fmt"

	pgx "github.com/jackc/pgx/v5"
	"github.com/nais/api/internal/graph/gengql"
	"github.com/nais/api/internal/graph/loader"
	"github.com/nais/api/internal/graph/model"
	"github.com/nais/api/internal/graph/scalar"
	"github.com/nais/api/internal/slug"
)

// ID is the resolver for the id field.
func (r *envResolver) ID(ctx context.Context, obj *model.Env) (*scalar.Ident, error) {
	id := scalar.EnvIdent(obj.Name)
	return &id, nil
}

// Namespace is the resolver for the namespace field.
func (r *envResolver) Namespace(ctx context.Context, obj *model.Env) (*string, error) {
	if obj.DBType == nil {
		te, err := loader.GetTeamEnvironment(ctx, slug.Slug(obj.Team), obj.Name)
		if err != nil {
			if errors.Is(err, pgx.ErrNoRows) {
				return nil, nil
			}
			return nil, err
		}
		obj = te
	}

	return obj.DBType.Namespace, nil
}

// GcpProjectID is the resolver for the gcpProjectID field.
func (r *envResolver) GcpProjectID(ctx context.Context, obj *model.Env) (*string, error) {
	if obj.DBType == nil {
		te, err := loader.GetTeamEnvironment(ctx, slug.Slug(obj.Team), obj.Name)
		if err != nil {
			if errors.Is(err, pgx.ErrNoRows) {
				return nil, nil
			}
			return nil, err
		}
		obj = te
	}

	return obj.DBType.GcpProjectID, nil
}

// SlackAlertsChannel is the resolver for the slackAlertsChannel field.
func (r *envResolver) SlackAlertsChannel(ctx context.Context, obj *model.Env) (string, error) {
	if obj.DBType == nil {
		te, err := loader.GetTeamEnvironment(ctx, slug.Slug(obj.Team), obj.Name)
		if err != nil {
			if errors.Is(err, pgx.ErrNoRows) {
				team, err := loader.GetTeam(ctx, slug.Slug(obj.Team))
				if err != nil {
					return "", fmt.Errorf("unable to load team: %w", err)
				}
				return team.SlackChannel, nil
			}
			return "", err
		}
		obj = te
	}

	return *obj.DBType.SlackAlertsChannel, nil
}

// Env returns gengql.EnvResolver implementation.
func (r *Resolver) Env() gengql.EnvResolver { return &envResolver{r} }

type envResolver struct{ *Resolver }
