package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/nais/api/internal/graph/model"
)

// DependencyTrackProject is the resolver for the dependencyTrackProject field.
func (r *queryResolver) DependencyTrackProject(ctx context.Context, projectID string) (*model.Image, error) {
	return r.dependencyTrackClient.GetFindingsForImageByProjectID(ctx, projectID)
}
