package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/nais/api/internal/graph/gengql"
	"github.com/nais/api/internal/graph/model"
)

// AnalysisTrail is the resolver for the analysisTrail field.
func (r *findingResolver) AnalysisTrail(ctx context.Context, obj *model.Finding) (*model.AnalysisTrail, error) {
	return r.dependencyTrackClient.GetAnalysisTrailForImage(ctx, obj.ParentID, obj.ComponentID, obj.VulnerabilityID)
}

// Findings is the resolver for the findings field.
func (r *imageResolver) Findings(ctx context.Context, obj *model.Image, offset *int, limit *int, orderBy *model.OrderBy) (*model.FindingList, error) {
	findings, err := r.dependencyTrackClient.GetFindingsForImageByProjectID(ctx, obj.ProjectID, true)
	if err != nil {
		return nil, err
	}

	if orderBy != nil {
		switch orderBy.Field {
		case model.OrderByFieldName:
			model.SortWith(findings, func(a, b *model.Finding) bool {
				return model.Compare(a.VulnerabilityID, b.VulnerabilityID, orderBy.Direction)
			})
		case model.OrderByFieldSeverity:
			model.SortWith(findings, func(a, b *model.Finding) bool {
				severityToScore := map[string]int{
					"CRITICAL":   5,
					"HIGH":       4,
					"MEDIUM":     3,
					"LOW":        2,
					"UNASSIGNED": 1,
				}

				if orderBy.Direction == model.SortOrderAsc {
					return severityToScore[a.Severity] < severityToScore[b.Severity]
				}

				return severityToScore[a.Severity] > severityToScore[b.Severity]
			})
		case model.OrderByFieldPackageURL:
			model.SortWith(findings, func(a, b *model.Finding) bool {
				return model.Compare(a.PackageURL, b.PackageURL, orderBy.Direction)
			})
		case model.OrderByFieldState:
			model.SortWith(findings, func(a, b *model.Finding) bool {
				return model.Compare(a.State, b.State, orderBy.Direction)
			})
		}
	}

	pagination := model.NewPagination(offset, limit)
	findings, pageInfo := model.PaginatedSlice(findings, pagination)

	return &model.FindingList{
		Nodes:    findings,
		PageInfo: pageInfo,
	}, nil
}

// SuppressFinding is the resolver for the suppressFinding field.
func (r *mutationResolver) SuppressFinding(ctx context.Context, analysisState string, comment string, componentID string, projectID string, vulnerabilityID string, suppressedBy string, suppress bool) (*model.AnalysisTrail, error) {
	options := []string{
		"IN_TRIAGE",
		"RESOLVED",
		"FALSE_POSITIVE",
		"NOT_AFFECTED",
	}

	var valid bool
	for _, o := range options {
		if analysisState == o {
			valid = true
			break
		}
	}

	if _, err := uuid.Parse(componentID); err != nil {
		return nil, fmt.Errorf("invalid component ID: %s", componentID)
	}
	if _, err := uuid.Parse(projectID); err != nil {
		return nil, fmt.Errorf("invalid project ID: %s", projectID)
	}
	if _, err := uuid.Parse(vulnerabilityID); err != nil {
		return nil, fmt.Errorf("invalid vulnerability ID: %s", vulnerabilityID)
	}

	if !valid {
		return nil, fmt.Errorf("invalid analysis state: %s", analysisState)
	}

	trail, err := r.dependencyTrackClient.SuppressFinding(ctx, analysisState, comment, componentID, projectID, vulnerabilityID, suppressedBy, suppress)
	if err != nil {
		return nil, err
	}

	return trail, nil
}

// DependencyTrackProject is the resolver for the dependencyTrackProject field.
func (r *queryResolver) DependencyTrackProject(ctx context.Context, projectID string) (*model.Image, error) {
	image, err := r.dependencyTrackClient.GetMetadataForImageByProjectID(ctx, projectID)
	if err != nil {
		return nil, err
	}

	for _, ref := range image.WorkloadReferences {
		app, err := r.k8sClient.App(ctx, ref.Name, ref.Team, ref.Environment)
		if err != nil {
			continue
		}
		if app == nil {
			continue
		}
		ref.DeployInfo = app.DeployInfo
	}

	return image, nil
}

// Finding returns gengql.FindingResolver implementation.
func (r *Resolver) Finding() gengql.FindingResolver { return &findingResolver{r} }

// Image returns gengql.ImageResolver implementation.
func (r *Resolver) Image() gengql.ImageResolver { return &imageResolver{r} }

type (
	findingResolver struct{ *Resolver }
	imageResolver   struct{ *Resolver }
)

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *imageResolver) ID(ctx context.Context, obj *model.Image) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}
