package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"github.com/nais/api/internal/graph/gengql"
	"github.com/nais/api/internal/graph/model"
	"github.com/nais/api/internal/slug"
)

// CreateSecret is the resolver for the createSecret field.
func (r *mutationResolver) CreateSecret(ctx context.Context, name string, team slug.Slug, env string, data []*model.SecretTupleInput) (*model.Secret, error) {
	panic(fmt.Errorf("not implemented: CreateSecret - createSecret"))
}

// UpdateSecret is the resolver for the updateSecret field.
func (r *mutationResolver) UpdateSecret(ctx context.Context, name string, team slug.Slug, env string, data []*model.SecretTupleInput) (*model.Secret, error) {
	panic(fmt.Errorf("not implemented: UpdateSecret - updateSecret"))
}

// DeleteSecret is the resolver for the deleteSecret field.
func (r *mutationResolver) DeleteSecret(ctx context.Context, name string, team slug.Slug, env string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteSecret - deleteSecret"))
}

// Secrets is the resolver for the secrets field.
func (r *queryResolver) Secrets(ctx context.Context, team slug.Slug) ([]*model.Secret, error) {
	return r.k8sClient.Secrets(ctx, team.String())
}

// Secret is the resolver for the secret field.
func (r *queryResolver) Secret(ctx context.Context, name string, team slug.Slug, env string) (*model.Secret, error) {
	panic(fmt.Errorf("not implemented: Secret - secret"))
}

// Data is the resolver for the data field.
func (r *secretResolver) Data(ctx context.Context, obj *model.Secret) ([]*model.SecretTuple, error) {
	panic(fmt.Errorf("not implemented: Data - data"))
}

// Secret returns gengql.SecretResolver implementation.
func (r *Resolver) Secret() gengql.SecretResolver { return &secretResolver{r} }

type secretResolver struct{ *Resolver }
