#!/usr/bin/env sh
#MISE description="Test all code"
#USAGE flag "--coverage" help="Generate a coverage profile"

set -e

# shellcheck disable=SC2154
if [ "$usage_coverage" = "true" ]; then
	rm -f hack/coverprofile.txt
	go test -coverprofile=hack/coverprofile.txt -coverpkg github.com/nais/api/... -v -tags integration_test --race ./integration_tests
else
	go test -cover -tags integration_test --race ./... github.com/nais/api/pkg/apiclient/...
fi
