apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: app-todo
spec:
  image: europe-north1-docker.pkg.dev/nais/navikt/app-name:latest
  ingresses:
    - "https://foo.dev-gcp.nais.io"
    - "https://bar.dev-gcp.nais.io"
    - "https://valid.nav.no"
---
apiVersion: v1
kind: Pod
metadata:
  name: app-todo-1
  labels:
    app: app-todo
  creationTimestamp: "2021-09-30T12:00:00Z"
spec:
  containers:
    - name: app-todo
      image: europe-north1-docker.pkg.dev/nais/navikt/app-name:latest
status:
  containerStatuses:
    - name: app-todo
      ready: true
      restartCount: 0
      state:
        running:
          startedAt: "2022-07-06T09:45:18Z"
