name: Build and push image and chart
on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore: [data/**]
  workflow_dispatch:
env:
  NAME: nais-api
  IMAGE_REPOSITORY: oci://europe-north1-docker.pkg.dev/nais-io/nais
jobs:
  test:
    name: Check pull request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          cache_key_prefix: mise-test
      - uses: ./.github/actions/go-cache
        with:
          key: test
      - run: mise run build:api
      - run: mise run test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          cache_key_prefix: mise-lint
      - uses: ./.github/actions/go-cache
        with:
          key: lint
          restore-keys: test
      - run: helm lint --strict ./charts
      - run: mise run check:staticcheck
      - run: mise run check:vulncheck
      - name: Check code format and run code generators
        run: |
          mise run fmt ::: generate
          echo "checking for diff after running generators and formatters, if this fails, run 'mise run fmt'"
          git diff --exit-code --name-only

  build_push:
    permissions:
      contents: read
      id-token: write
    if: github.triggering_actor != 'dependabot[bot]'
    name: Build and push
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.build-push-sign.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          cache_key_prefix: mise-build-push
      - uses: ./.github/actions/go-cache
        with:
          key: build
          restore-keys: test
      - run: mise run build:api
      - uses: nais/platform-build-push-sign@docker_cache
        id: build-push-sign
        with:
          name: nais-api
          dockerfile: Dockerfile.ci
          google_service_account: gh-api
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
          push: true
      - name: Build Chart
        run: |-
          sed -i "s/^version: .*/version: ${{ steps.build-push-sign.outputs.version }}/g" charts/Chart.yaml
          cat charts/Chart.yaml
          helm package charts
      - name: Push Chart
        run: |-
          helm push ${{ env.NAME }}*.tgz ${{ env.IMAGE_REPOSITORY }}

  rollout:
    needs:
      - test
      - lint
      - build_push
    runs-on: fasit-deploy
    if: github.ref == 'refs/heads/main'
    permissions:
      id-token: write
    steps:
      - uses: nais/fasit-deploy@v2
        with:
          chart: ${{ env.IMAGE_REPOSITORY }}/${{ env.NAME }}
          version: ${{ needs.build_push.outputs.version }}
