name: Build and push image and chart
on:
  push:
    branches:
      - main
jobs:
  build_push:
    outputs:
      version: ${{ steps.build-push-sign.outputs.version }}
    permissions:
      contents: read
      id-token: write
    name: Build and push
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Find Go version
        id: go_version
        run: echo "GO_VERSION=$(grep golang .tool-versions | awk '{print $2}')" >> $GITHUB_OUTPUT
      - uses: asdf-vm/actions/install@v3
        with:
          before_install: |
            asdf install golang latest
            asdf global golang latest

      - run: go test ./...
      # - run: helm lint --strict ./charts
      - run: make check
      - run: |
          make fmt
          make generate
          git diff --exit-code --name-only
