name: Build and push image and chart
on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore: [data/**]
  workflow_dispatch:
env:
  NAME: nais-api
  IMAGE_REPOSITORY: oci://europe-north1-docker.pkg.dev/nais-io/nais
jobs:
  test:
    name: Check pull request
    runs-on: ubuntu-latest-8-cores
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v4
        with:
          cache_key_prefix: mise-test
      - uses: ./.github/actions/go-cache
        with:
          key: test
      - run: mise run build:api
      - run: mise run test

  lint:
    name: Lint
    runs-on: ubuntu-latest-8-cores
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v4
        with:
          cache_key_prefix: mise-lint
      - uses: ./.github/actions/go-cache
        with:
          key: lint
          restore-keys: test
      - run: helm lint --strict ./charts/*
      - run: mise run check:staticcheck
      - name: Vulnerability check (govulncheck) # Temporary allow-fail due to GO-2026-5662
        run: mise run check:vulncheck
        continue-on-error: true
      - name: Check code format and run code generators
        id: check-format-and-generate
        run: |
          mise run fmt ::: generate
          echo "checking for diff after running generators and formatters, if this fails, run 'mise run generate' and 'mise run fmt' locally and commit the changes"
          git diff --exit-code --name-only
      - name: Report failure
        if: failure() && steps.check-format-and-generate.outcome == 'failure'
        run: |
          echo "Linting failed. Please fix the issues and try again."
          echo "You can run 'mise run generate' and 'mise run fmt' locally to fix formatting and code generation issues."
          echo "In some instances, there might be other issues that need manual intervention. See the changed files in the previous step for more details."
          exit 1

  build_push:
    permissions:
      contents: read
      id-token: write
    if: github.triggering_actor != 'dependabot[bot]'
    name: Build and push
    runs-on: ubuntu-latest-8-cores
    outputs:
      version: ${{ steps.build-push-sign.outputs.version }}
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v4
        with:
          cache_key_prefix: mise-build-push
      - uses: ./.github/actions/go-cache
        with:
          key: build
          restore-keys: test
      - run: mise run build:api
      - uses: nais/platform-build-push-sign@main # ratchet:exclude
        id: build-push-sign
        with:
          name: nais-api
          dockerfile: Dockerfile.ci
          google_service_account: gh-api
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
          push: true
      - name: Build Chart
        run: |-
          sed -i "s/^version: .*/version: ${{ steps.build-push-sign.outputs.version }}/g" charts/nais-api/Chart.yaml
          cat charts/nais-api/Chart.yaml
          helm package charts/nais-api
      - name: Push Chart
        run: |-
          helm push ${{ env.NAME }}*.tgz ${{ env.IMAGE_REPOSITORY }}

  deploy:
    name: Deploy
    needs:
      - test
      - lint
      - build_push
    runs-on: fasit-deploy
    if: github.ref == 'refs/heads/main'
    permissions:
      id-token: write
    steps:
      - uses: nais/fasit-deploy@58a70a338b16dc646373c91724fc7e7522d085a4 # ratchet:nais/fasit-deploy@v4.0.1
        with:
          chart: ${{ env.IMAGE_REPOSITORY }}/${{ env.NAME }}
          version: ${{ needs.build_push.outputs.version }}
          targets: |
            [
              { "target": { "kind": "management", "tenant": "ci-nais" }, "wait": true },
              { "target": { "kind": "management" } }
            ]
