name: Check pull request
on: pull_request
jobs:
  test:
    name: Check pull request
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v3
        with:
          before_install: |
            asdf install golang latest
            asdf global golang latest

      - run: go test ./...
      - run: helm lint --strict ./charts
      - run: make staticcheck
      - run: make vulncheck
      - run: make deadcode
      - run: |
          make fmt
          make generate
          git diff --exit-code --name-only