name: Check pull request
on: pull_request
env:
  NAME: nais-api
  IMAGE_REPOSITORY: oci://europe-north1-docker.pkg.dev/nais-io/nais
jobs:
  test:
    name: Check pull request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - name: Find go cache dir
        id: go-cache
        run: |
          echo "gocache=$(go env GOCACHE)" >> $GITHUB_OUTPUT
          echo "gomodcache=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT
      - name: Cache go modules
        uses: actions/cache@v4
        with:
          path: |
            ${{ steps.go-cache.outputs.gocache }}
            ${{ steps.go-cache.outputs.gomodcache }}
          key: ${{ runner.os }}-go-pr-${{ hashFiles('**/go.sum') }}
      - run: mise run test
      - name: Trim Go cache
        if: ${{ github.ref == 'refs/heads/main' }}
        shell: bash
        # As the go command works, it either creates build cache files or touches
        # ones it uses at most once an hour. When it trims the cache, it trims
        # files that have not been modified/touched in 5+ days.
        # To keep our saved cache lean, trim all files except ones that were just
        # created/touched as part of this run.
        run: |
          find ~/.cache/go-build -type f -mmin +90 -delete

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - name: Find go cache dir
        id: go-cache
        run: |
          echo "gocache=$(go env GOCACHE)" >> $GITHUB_OUTPUT
          echo "gomodcache=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT
      - name: Cache go modules
        uses: actions/cache@v4
        with:
          path: |
            ${{ steps.go-cache.outputs.gocache }}
            ${{ steps.go-cache.outputs.gomodcache }}
          key: ${{ runner.os }}-go-lint-${{ hashFiles('**/go.sum') }}
      - run: helm lint --strict ./charts
      - run: mise run check:staticcheck
      - run: mise run check:vulncheck
      - name: Check code format and run code generators
        run: |
          mise run fmt ::: generate
          go mod tidy
          git diff --exit-code --name-only

  build_push:
    outputs:
      version: ${{ steps.build-push-sign.outputs.version }}
    permissions:
      contents: read
      id-token: write
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          cache: false
          install: false
      - id: go_version
        run: echo "go_version=$(mise current go)" >> $GITHUB_OUTPUT
      - name: Cache go modules
        uses: actions/cache@v4
        with:
          path: |
            .cache
          key: ${{ runner.os }}-docker-dance-${{ hashFiles('Dockerfile') }}
      - uses: nais/platform-build-push-sign@docker_cache
        id: build-push-sign
        with:
          name: nais-api
          build_args: |
            GO_VERSION=${{ steps.go_version.outputs.go_version }}-
          google_service_account: gh-api
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
          push: true
          cache_from: type=local,src=.cache
          cache_to: type=local,dest=.cache
      - name: Build Chart
        run: |-
          sed -i "s/^version: .*/version: ${{ steps.build-push-sign.outputs.version }}/g" charts/Chart.yaml
          cat charts/Chart.yaml
          helm package charts
      - name: Push Chart
        run: |-
          helm push ${{ env.NAME }}*.tgz ${{ env.IMAGE_REPOSITORY }}
