name: Check pull request
on: pull_request
jobs:
  test:
    name: Check pull request
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/setup@v3
      - id: asdf-cache
        uses: actions/cache@v4
        with:
          path: ~/.asdf/
          key: ${{ runner.os }}-asdf-${{ hashFiles('**/.tool-versions') }}
      - uses: asdf-vm/actions/install@v3
        if: steps.asdf-cache.outputs.cache-hit != 'true'
        with:
          before_install: |
            asdf install golang latest
            asdf global golang latest
      - name: Find go cache dir
        id: go-cache
        run: |
          go version
          # Clear cache dirs to avoid error when restoring
          go clean -cache -modcache
          echo "gocache=$(go env GOCACHE)" >> $GITHUB_OUTPUT
          echo "gomodcache=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT
      - name: Cache go modules
        uses: actions/cache@v4
        with:
          path: |
            ${{ steps.go-cache.outputs.gocache }}
            ${{ steps.go-cache.outputs.gomodcache }}
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - run: go test ./...
      - run: helm lint --strict ./charts
      - run: make staticcheck
      - run: make vulncheck
      - name: Check code format and run code generators
        run: |
          make fmt
          make generate
          git diff --exit-code --name-only