name: Check pull request
on: pull_request
env:
  NAME: nais-api
  IMAGE_REPOSITORY: oci://europe-north1-docker.pkg.dev/nais-io/nais
jobs:
  test:
    name: Check pull request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - uses: ./.github/actions/go-cache
        with:
          key: pr
      - run: mise run test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - uses: ./.github/actions/go-cache
        with:
          key: lint
      - run: helm lint --strict ./charts
      - run: mise run check:staticcheck
      - run: mise run check:vulncheck
      - name: Check code format and run code generators
        run: |
          mise run fmt ::: generate
          go mod tidy
          git diff --exit-code --name-only

  build_push:
    permissions:
      contents: read
      id-token: write
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - uses: ./.github/actions/go-cache
        with:
          key: pr
      - run: mise run build:api
      - uses: nais/platform-build-push-sign@docker_cache
        id: build-push-sign
        with:
          name: nais-api
          dockerfile: Dockerfile.ci
          google_service_account: gh-api
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
          push: true
      - name: Build Chart
        run: |-
          sed -i "s/^version: .*/version: ${{ steps.build-push-sign.outputs.version }}/g" charts/Chart.yaml
          cat charts/Chart.yaml
          helm package charts
      - name: Push Chart
        run: |-
          helm push ${{ env.NAME }}*.tgz ${{ env.IMAGE_REPOSITORY }}
