---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/mutable-but-unreadable-fields: "{}"
    cnrm.cloud.google.com/observed-secret-versions: "{}"
    cnrm.cloud.google.com/project-id: nais-dev-2e7b
    cnrm.cloud.google.com/state-into-spec: merge
    nais.io/deploymentCorrelationID: audit-test-correlation-id
  name: audit-enabled
spec:
  databaseVersion: POSTGRES_15
  instanceType: CLOUD_SQL_INSTANCE
  maintenanceVersion: POSTGRES_15_10.R20240130.00_05
  region: europe-north1
  resourceID: audit-enabled
  settings:
    activationPolicy: ALWAYS
    availabilityType: ZONAL
    backupConfiguration:
      backupRetentionSettings:
        retainedBackups: 7
        retentionUnit: COUNT
      enabled: true
      pointInTimeRecoveryEnabled: false
      startTime: "02:00"
      transactionLogRetentionDays: 7
    connectorEnforcement: NOT_REQUIRED
    databaseFlags:
      - name: cloudsql.iam_authentication
        value: "on"
      - name: cloudsql.enable_pgaudit
        value: "on"
    diskAutoresize: false
    diskSize: 10
    diskType: PD_SSD
    insightsConfig:
      queryInsightsEnabled: true
      queryStringLength: 1024
      recordApplicationTags: false
      recordClientAddress: false
    ipConfiguration:
      ipv4Enabled: true
      requireSsl: true
    locationPreference:
      zone: europe-north1-a
    pricingPlan: PER_USE
    tier: db-f1-micro
---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/mutable-but-unreadable-fields: "{}"
    cnrm.cloud.google.com/observed-secret-versions: "{}"
    cnrm.cloud.google.com/project-id: nais-dev-2e7b
    cnrm.cloud.google.com/state-into-spec: merge
    nais.io/deploymentCorrelationID: audit-test-correlation-id
  name: audit-disabled
spec:
  databaseVersion: POSTGRES_15
  instanceType: CLOUD_SQL_INSTANCE
  maintenanceVersion: POSTGRES_15_10.R20240130.00_05
  region: europe-north1
  resourceID: audit-disabled
  settings:
    activationPolicy: ALWAYS
    availabilityType: ZONAL
    backupConfiguration:
      backupRetentionSettings:
        retainedBackups: 7
        retentionUnit: COUNT
      enabled: true
      pointInTimeRecoveryEnabled: false
      startTime: "02:00"
      transactionLogRetentionDays: 7
    connectorEnforcement: NOT_REQUIRED
    databaseFlags:
      - name: cloudsql.iam_authentication
        value: "on"
      - name: cloudsql.enable_pgaudit
        value: "off"
    diskAutoresize: false
    diskSize: 10
    diskType: PD_SSD
    insightsConfig:
      queryInsightsEnabled: true
      queryStringLength: 1024
      recordApplicationTags: false
      recordClientAddress: false
    ipConfiguration:
      ipv4Enabled: true
      requireSsl: true
    locationPreference:
      zone: europe-north1-a
    pricingPlan: PER_USE
    tier: db-f1-micro
---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/mutable-but-unreadable-fields: "{}"
    cnrm.cloud.google.com/observed-secret-versions: "{}"
    cnrm.cloud.google.com/project-id: nais-dev-2e7b
    cnrm.cloud.google.com/state-into-spec: merge
    nais.io/deploymentCorrelationID: audit-test-correlation-id
  name: no-audit-flag
spec:
  databaseVersion: POSTGRES_15
  instanceType: CLOUD_SQL_INSTANCE
  maintenanceVersion: POSTGRES_15_10.R20240130.00_05
  region: europe-north1
  resourceID: no-audit-flag
  settings:
    activationPolicy: ALWAYS
    availabilityType: ZONAL
    backupConfiguration:
      backupRetentionSettings:
        retainedBackups: 7
        retentionUnit: COUNT
      enabled: true
      pointInTimeRecoveryEnabled: false
      startTime: "02:00"
      transactionLogRetentionDays: 7
    connectorEnforcement: NOT_REQUIRED
    databaseFlags:
      - name: cloudsql.iam_authentication
        value: "on"
    diskAutoresize: false
    diskSize: 10
    diskType: PD_SSD
    insightsConfig:
      queryInsightsEnabled: true
      queryStringLength: 1024
      recordApplicationTags: false
      recordClientAddress: false
    ipConfiguration:
      ipv4Enabled: true
      requireSsl: true
    locationPreference:
      zone: europe-north1-a
    pricingPlan: PER_USE
    tier: db-f1-micro
